# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
# export LS_OPTIONS='--color=auto'
# eval "$(dircolors)"
# alias ls='ls $LS_OPTIONS'
# alias ll='ls $LS_OPTIONS -l'
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'


alias asterisk_logs='podman logs -f oml-asterisk-server'
alias postgres_logs='podman logs -f oml-asterisk-server'
alias kamailio_logs='podman logs -f oml-kamailio-server'
alias rtpengine_logs='podman logs -f oml-kamailio-server'
alias django_logs='podman logs -f oml-django-server'
alias redis_logs='podman logs -f oml-redis-server'
alias postgres_logs='podman logs -f oml-postgresql-server'
alias websockets_logs='podman logs -f oml-websockets-server'
alias nginx_logs='podman logs -f oml-nginx-server'

alias asterisk_terminal='podman exec -it oml-asterisk-server bash'
alias postgres_terminal='podman exec -it oml-asterisk-server bash'
alias kamailio_terminal='podman exec -it -it oml-kamailio-server bash'
alias rtpengine_terminal='podman exec -it oml-kamailio-server bash'
alias django_terminal='podman exec -it oml-django-server bash'
alias redis_terminal='podman exec -it oml-redis-server bash'
alias postgres_terminal='podman exec -it oml-postgresql-server bash'
alias websockets_terminal='podman exec -it oml-websockets-server bash'
alias nginx_terminal='podman exec -it oml-nginx-server sh'
