# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can nginxtribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: POSTGRESQL component delpoy
  hosts: omnileads-sql
  tags:
    - all_components
    - app
    - postgres

  vars:
    img_repo: '{{ container_image_registry }}/omnileads/postgres'
    img_prometheus_repo: 'docker.io/prometheuscommunity/postgres-exporter'

  tasks:

    - name: POSTGRESQL Set environment variables for this installation
      template:
        src: "{{ pgsql_repo_path }}templates/postgres.env"
        dest: /etc/default/postgres.env
        mode: 664
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL Copy systemd file
      template:
        src: "{{ pgsql_repo_path }}templates/postgresql.service"
        dest: /etc/systemd/system/postgresql.service
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL Pull image
      command: podman pull --quiet {{ img_repo }}:{{ postgres_version }}
      register: podman_pull
      until: podman_pull is success
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL Enable and start service
      systemd:
        name: postgresql.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL prometheus Set environment variables for this installation
      template:
        src: "{{ pgsql_repo_path }}templates/prometheus.env"
        dest: /etc/default/prometheus_postgres.env
        mode: 664
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL prometheus Copy systemd file
      template:
        src: "{{ pgsql_repo_path }}templates/prometheus.service"
        dest: /etc/systemd/system/prometheus_postgres.service
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL prometheus Pull image
      command: podman pull --quiet {{ img_prometheus_repo }}
      register: podman_pull
      until: podman_pull is success
      tags:
        - install
        - upgrade
        - postgres

    - name: POSTGRESQL prometheus Enable and start service
      systemd:
        name: prometheus_postgres.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags:
        - install
        - upgrade
        - postgres
