stages:
  - deploy


deploy-aio-digitalocean:
  stage: deploy
  image: omnileads/doctl:230427.01
  variables: 
    DIGITALOCEAN_ACCESS_TOKEN: $DIGITALOCEAN_ACCESS_TOKEN
    DIGITALOCEAN_DROPLET_IMG: $DIGITALOCEAN_DROPLET_IMG
    DIGITALOCEAN_DROPLET_SIZE: $DIGITALOCEAN_DROPLET_SIZE
    DIGITALOCEAN_REGION: $DIGITALOCEAN_REGION
    DIGITALOCEAN_SSH_KEY: $DIGITALOCEAN_SSH_KEY
  script:
    - doctl auth init -t ${DIGITALOCEAN_ACCESS_TOKEN}
    - git clone --branch $CI_COMMIT_BRANCH https://gitlab.com/omnileads/omldeploytool.git ~/omldeploytool    
    - doctl compute droplet create --image $DIGITALOCEAN_DROPLET_IMG --size $DIGITALOCEAN_DROPLET_SIZE --region $DIGITALOCEAN_REGION --ssh-keys $DIGITALOCEAN_SSH_KEY --user-data-file ~/omldeploytool/docker-compose/user-data.sh cicd-aio.$CI_JOB_ID
    - sleep 60
    - OML_IPADDR=$(doctl compute droplet list |grep cicd-aio.$CI_JOB_ID |awk '{print $3}') && echo "$OML_IPADDR to run tests"
    - until curl -sk --head --request GET https://$OML_IPADDR |grep "302" > /dev/null; do echo "Environment still being installed, sleeping 60 seconds"; sleep 60; done; echo "Environment is up"
    - sleep 360
    - doctl compute droplet delete -f cicd-aio.$CI_JOB_ID
    - rm -rf omldeploytool
  only:
    - /.*pipeline-aio.*$/
    - /.*pipeline-all.*$/
    - schedules
    - web
