stages:
  - deploy


deploy-aio-digitalocean:
  stage: deploy
  image: omnileads/doctl:230427.01
  variables: 
    - DIGITALOCEAN_ACCESS_TOKEN: $DIGITALOCEAN_ACCESS_TOKEN    
  script:
    - doctl auth init --access-token ${DIGITALOCEAN_ACCESS_TOKEN}
    - git clone --branch $CI_COMMIT_BRANCH https://gitlab.com/omnileads/omldeploytool.git ~/omldeploytool    
    - doctl compute droplet create --image debian-11-x64 --size s-2vcpu-4gb --region sfo3 --ssh-keys 53:14:f8:0f:07:45:a7:35:36:b2:9f:c4:a7:c3:6f:54 --user-data-file ~/omldeploytool/docker-compose/user-data.sh cicd-aio.$CI_JOB_ID
    #- doctl compute droplet create --image $DIGITALOCEAN_DROPLET_IMG --size $DIGITALOCEAN_DROPLET_SIZE --region $DIGITALOCEAN_REGION --ssh-keys $DIGITALOCEAN_SSH_KEY --user-data-file ~/omldeploytool/docker-compose/user-data.sh cicd-aio.$CI_JOB_ID
    - sleep 60
    - IP=$(doctl compute droplet list |grep cicd-aio.$CI_JOB_ID |awk '{print $3}') && echo "$IP 2 run tests"
    - until curl -sk --head  --request GET https://$IP |grep "302" > /dev/null; do echo "Environment still being installed, sleeping 80 seconds"; sleep 80; done; echo "Environment is up"
    - sleep 360
    - doctl compute droplet delete -f cicd-aio.$CI_JOB_ID
    - rm -rf omldeploytool
  only:
    - /.*pipeline-aio.*$/
    - /.*pipeline-all.*$/
    - schedules
    - web
