# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: MAIN Install required Debian packages
  apt:
    name:
      - curl
      - net-tools
      - wget
      - jq
      - sngrep
      - awscli
      - python3-boto3
      - python3-psycopg2
      - postgresql-client
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"
  tags: 
    - install
    - voice
    - asterisk
    - app
    - observability

- name: MAIN Enable EPEL Repository on Rocky Linux
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['distribution'] == "Rocky" 
  tags: 
    - install
    - postgres
    - voice
    - app
    - observability
    - asterisk

- name: MAIN Install required Rocky Linux packages
  dnf:
    name:
      - python3
      - python3-pip
      - jq
      - postgresql
      - python3-psycopg2
      - python3-boto3
      - awscli
      - libselinux-python3
    state: latest
  when: ansible_facts['distribution'] == "Rocky" 
  tags: 
    - install
    - postgres
    - voice
    - app
    - observability
    - asterisk

- name: MAIN Install required Centos7 SQL packages
  yum:
    name:
      - git 
      - epel-release 
      - libselinux-python3
      - python3
      - python3-pip
      - podman
    state: latest
  when: ansible_facts['distribution'] == "CentOS" 
  tags: 
    - install
    - postgres

- name: MAIN Disable SELinux Rocky Linux
  selinux:
    state: disabled
  when: (ansible_os_family == "AlmaLinux") or (ansible_os_family == "Rocky") or (ansible_os_family == "CentOS") 
  tags: 
    - install
    - voice
    - app
    - observability
    - asterisk

# --- install DOCKER
- name: MAIN Descargar el script de instalación de Docker
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
  tags:
    - install
  when:
    - docker_compose is defined   

- name: MAIN Ejecutar el script de instalación de Docker
  command: sh /tmp/get-docker.sh
  tags:
    - install
  when:
    - docker_compose is defined   

- name: MAIN Agregar el usuario al grupo de Docker
  user:
    name: '{{ usuario }}'
    groups: docker
  tags:
    - install
    - upgrade
  when:
    - docker_compose is defined   

- name: MAIN Reiniciar el servicio de Docker
  systemd:
    name: docker
    state: restarted
  tags:
    - install  
  when:
    - docker_compose is defined   

- name: MAIN docker-compose link bin
  file: 
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link 
  tags:
    - install  
  when:
    - docker_compose is defined   

- name: MAIN add docker-plugin Loki logs
  command: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
  tags:
    - install
  when:
    - docker_compose is defined 


# --- install PODMAN
- name: MAIN Install PODMAN
  apt:
    name:
      - podman
    update_cache: yes
    state: latest
  when: 
     - ansible_os_family == "Debian"
     - docker_compose is not defined
  tags: 
    - install
    - voice
    - asterisk
    - app
    - observability

- name: MAIN Install PODMAN
  dnf:
    name:
      - podman
    state: latest
  when: 
    - ansible_facts['distribution'] == "Rocky" 
    - docker_compose is not defined
  tags: 
    - install
    - postgres
    - voice
    - app
    - observability
    - asterisk

- name: MAIN Check if Omnileads has been installed previously
  include: checks.yml
  
- name: MAIN First configuration in server or servers
  include: os_configuration.yml


