# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se instala net-tools necesario para obtener la subnet privada
# - name: Upgrade all packages on servers
#   apt:
#     update: dist
#

- name: MAIN Install required Debian packages
  apt:
    name:
      - curl
      - net-tools
      - podman
      - wget
      - jq
      - sngrep
      - awscli
      - python3-boto3
      - python3-psycopg2
      - postgresql-client
    update_cache: yes
    state: latest
  tags: install
  when: ansible_distribution == "Debian"

- name: MAIN Enable EPEL Repository on Rocky Linux
  dnf:
    name: epel-release
    state: latest
  tags: install
  when: ansible_distribution == "Rocky"

- name: MAIN enable postgres dnf module ROCKY
  command: 'dnf -y module enable postgresql:{{ postgres_version }}'
  tags: install
  when: ansible_distribution == "Rocky"

- name: MAIN Install required Rocky Linux packages
  dnf:
    name:
      - python3
      - python3-pip
      - podman
      - jq
      - postgresql
      - python3-psycopg2
      - python3-boto3
      - awscli
    state: latest
  tags: install
  when: ansible_distribution == "Rocky"

- name: MAIN Disable SELinux Rocky Linux
  selinux:
    state: disabled
  tags: install
  when: ansible_distribution == "Rocky"

- name: MAIN Check if Omnileads has been installed previously
  include: checks.yml
  tags: always

- name: MAIN First configuration in server or servers
  include: os_configuration.yml
  tags:
    - install
    - upgrade

- name: MAIN Perform a backup
  include: backup.yml
  tags:
    - backup
