# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se instala net-tools necesario para obtener la subnet privada
# - name: Upgrade all packages on servers
#   apt:
#     update: dist
#


- name: MAIN Check if Omnileads has been installed previously
  include: checks.yml
  tags: always

- name: MAIN Perform a backup
  include: backup.yml
  tags:
    - backup

- name: MAIN First configuration in server or servers
  include: os_configuration.yml
  tags:
    - install
    - upgrade
