# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: Disable ufw
  systemd:
    name: ufw
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes

- name: Disable firewallD
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes

- name: Ensure group {{ usuario }} exists
  group:
    name: '{{ usuario }}'
    state: present
  tags: install

- name: Add the {{ usuario }} user
  user:
    name: '{{ usuario }}'
    group: '{{ usuario }}'
    comment: OMniLeads OS user
    shell: /bin/bash
    home: '{{ django_deploy_path }}'
  tags: install

- name: Creates /etc/omnileads directory
  file:
    path: /etc/omnileads
    state: directory
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0764
    recurse: yes
  when: etc_omnileads.stat.exists == false
  tags: install

- name: Creates /etc/omnileads/certs directory
  file:
    path: '{{ certs_location }}'
    state: directory
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0764
  when: etc_omnileads.stat.exists == false
  tags: install

- name: Creates /var/lib/omnileads directory
  file:
    path: '{{ asterisk_sounds_host_path }}'
    state: directory
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0764
    recurse: yes
  when: var_lib_omnileads.stat.exists == false
  tags:
    - install

- name: Creates /var/lib/omnileads/minio directory
  file:
    path: '{{ minio_persistent_path }}'
    state: directory
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0764
    recurse: yes
  when: var_lib_omnileads_minio.stat.exists == false
  tags:
    - install

- name: Creates /var/lib/omnileads/pgsql directory
  file:
    path: '{{ postgres_persistent_path }}'
    state: directory
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0764
    recurse: yes
  when: var_lib_omnileads_pgsql.stat.exists == false
  tags:
    - install

- name: Copy SSL certs
  copy:
    src: "certs/cert.pem"
    dest: /etc/omnileads/certs/cert.pem
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0777
  tags:
    - install
    - nginx
    - kamailio
    - asterisk

- name: Copy SSL certs
  copy:
    src: "templates/bashrc"
    dest: /root/.bashrc
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
    mode: 0777
  tags:
    - install

- name: Copy SSL certs
  copy:
    src: "certs/key.pem"
    dest: /etc/omnileads/certs/key.pem
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0777
  tags:
    - app
    - aio
    - nginx
    - kamailio
    - asterisk

- name: Copy oml_manage script
  template:
    src: "templates/oml_manage.sh"
    dest: /usr/local/bin/oml_manage.sh
    mode: 0755

# Se setea el timezone
- name: Set timezone of server
  timezone: name={{ TZ }}
  tags: install

- name: Copy CRONes
  template:
    src: "templates/crones"
    dest: /var/spool/cron/crontabs/root
    mode: 0600
  tags:
    - upgrade
  when:
    - app_host is not defined

- name: Pull crones image
  command: podman pull --quiet docker.io/omnileads/callrec_converter:latest
  register: podman_pull
  until: podman_pull is success
  tags:
    - upgrade
  when:
    - app_host is not defined

- name: Callrec container environment variables
  template:
    src: "templates/callrec_converter.env"
    dest: /etc/default/callrec_converter.env
    mode: 666
    owner: '{{ usuario }}'
    group: '{{ usuario }}'
  tags:
    - upgrade
  when:
    - app_host is not defined
