version: "3.0"

services:
  kamailio:
    image: omnileads/kamailio:oml-196
    deploy:
#      placement: 
#        constraints: 
#          - node.role != manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - ./certs:/etc/omnileads/certs
    env_file: ./kamailio.env
    