services:

  django_app:
    container_name: oml-app
    depends_on:
      - redis
      - acd    
    dns: 8.8.8.8
    env_file: .env
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/init_uwsgi.sh
    networks:
      - omnileads
    ports:
      - 8099:8099  
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto
    volumes:
      - django_static:/opt/omnileads/static
      - django_callrec_zip:/opt/omnileads/asterisk/var/spool/asterisk/monitor

  django_commands:
    depends_on:
      - redis
    dns: 8.8.8.8
    env_file: .env    
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/django_commands.sh
    networks:
      - omnileads
    privileged: true
    #restart: on-failure
    stdin_open: true
    stop_grace_period: 30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto
    volumes:
      - django_static:/opt/omnileads/static
      - django_callrec_zip:/opt/omnileads/asterisk/var/spool/asterisk/monitor

  daphne:
    container_name: oml-daphne
    depends_on:
      - redis
    dns: 8.8.8.8
    env_file: .env
    environment:
      - DAPHNE_ENABLE=True
      - DJANGO_HOSTNAME=daphne
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/init_daphne.sh
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    working_dir: /opt/omnileads/ominicontacto

  omlcron:
    container_name: oml-cron
    depends_on:
      - acd
      - redis
    dns: 8.8.8.8
    env_file: .env
    environment:
      - UWSGI_PORT=8097
      - DJANGO_HOSTNAME=omlcron
    image: ${OMLAPP_IMG}
    command: /opt/omnileads/bin/docker-entrypoint.sh
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    working_dir: /opt/omnileads

  fastagi:
    depends_on:
      - redis      
    image: ${OMLFASTAGI_IMG}
    container_name: oml-fastagi
    command: python /app/fastagi.py
    environment:
      - TZ=${TZ}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}    
    restart: on-failure
    networks:
      - omnileads

  ami:
    image: ${OMLAMI_IMG}
    depends_on:
      - acd
      - redis
    container_name: oml-astami
    environment:
      - TZ=${TZ}
      - ASTERISK_HOSTNAME=${ASTERISK_HOSTNAME}
      - AMI_USER=${AMI_USER}
      - AMI_PASSWORD=${AMI_PASSWORD}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
    restart: on-failure    
    networks:
      - omnileads

  acd_config_generator:
    image: ${OMLACD_RETRIEVE_CONF_IMG}
    container_name: oml-acd-conf
    depends_on:
      - websockets
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - ASTERISK_LOCATION=
      - ARI_HOST=${ASTERISK_HOSTNAME}
      - ARI_USER=${AMI_USER}
      - ARI_PASS=${AMI_PASSWORD}
      - OMNILEADS_HOSTNAME=${OMNILEADS_HOSTNAME}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    volumes:      
      - asterisk_conf:/home/omnileads/astconf
      - asterisk_sounds:/home/omnileads/sounds

  acd:
    image: ${OMLACD_IMG}
    container_name: oml-acd
    depends_on:
      - fastagi
    networks:
      omnileads:
        ipv4_address: ${ACD_CONTAINER_IPV4}
    environment:
      - TZ=${TZ}      
      - ENV=${ENV}
      - DIALER_HOST=${DIALER_SIP_ADDR}
      - RABBITMQ_HOST=${RABBITMQ_HOSTNAME}
      - FASTAGI=${FASTAGI_HOSTNAME}
      - AMI_USER=${AMI_USER}
      - AMI_PASSWORD=${AMI_PASSWORD}
      - HOMER_ENABLE=False
      - HOMERHOST=${HOMERHOST}
      - HOMERPORT=${HOMERPORT}
      - CALLREC_SPLIT_CHANNELS=${CALLREC_SPLIT_CHANNELS}
      - ASTERISK_HOSTNAME=${PRIVATE_IP}
    acd_container_ipv4: ${ACD_CONTAINER_IPV4}
    privileged: true
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - asterisk_callrec:/var/spool/asterisk/monitor/
      - asterisk_conf:/etc/asterisk/retrieve_conf
      - asterisk_sounds:/var/lib/asterisk/sounds/oml
      #- ./asterisk_custom/google_credential.json:/tmp/google_credential.json
      #- ./asterisk_custom/oml_extensions_custom.conf:/etc/asterisk/oml_extensions_custom.conf
    working_dir: /etc/asterisk

  interaction_processor:
    image: ${OMLINTERACTION_PROC_IMG}
    container_name: oml-post-interactions
    depends_on:
      - rabbitmq
      - acd
    dns: 8.8.8.8
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOSTNAME}
      - TZ=${TZ}
      - CALLREC_DEVICE=${CALLREC_DEVICE}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT_MINIO}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    command: python /app/app.py
    volumes:
      - asterisk_callrec:/var/spool/asterisk/monitor/
  
  kamailio:
    image: ${OMLKAM_IMG}
    container_name: oml-kamailio
    depends_on:
      - redis
      - acd
      - rtpengine
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - AUTHEPH_SK=${AUTHEPH_SK}
      - ASTERISK_HOSTNAME=${ASTERISK_HOSTNAME}
      - KAMAILIO_HOSTNAME=${KAMAILIO_HOSTNAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - RTPENGINE_HOSTNAME=${RTPENGINE_HOSTNAME}
      - SHM_SIZE=${SHM_SIZE}
      - PKG_SIZE=${PKG_SIZE}
      - KAMAILIO_CERTS_LOCATION=${KAMAILIO_CERTS_LOCATION}
    networks:
      - omnileads
    privileged: true
    restart: on-failure
    stop_grace_period: 10s

  nginx:
    image: ${OMLNGINX_IMG}
    container_name: oml-nginx
    depends_on:
      - django_app
      - daphne
      - kamailio
      - websockets
    dns: 8.8.8.8
    environment:
      - ENV=devenv
      - TZ=${TZ}
      - DJANGO_HOSTNAME=${DJANGO_HOSTNAME}
      - WSGI_PORT=8099
      - DAPHNE_HOSTNAME=${DJANGO_HOSTNAME}
      - ASGI_PORT=8099
      - KAMAILIO_HOSTNAME=${KAMAILIO_HOSTNAME}
      - KAMAILIO_PORT=14443
      - WEBSOCKETS_HOSTNAME=${WEBSOCKET_HOSTNAME}
      - WEBSOCKETS_PORT=8000
      - CALLREC_DEVICE=${CALLREC_DEVICE}
      - S3_ENDPOINT=${S3_ENDPOINT_MINIO}
      #- WEBUI_MODE=rproxy
      #- WALLBOARD_WEBUI_HOST=kamailio
    networks:
      - omnileads
    privileged: true
    ports:
      - ${NGINX_EXT_PORT}:443/tcp
    restart: on-failure
    stop_grace_period: 15s
    volumes:
      - django_static:/opt/omnileads/static
      - django_callrec_zip:/opt/omnileads/asterisk/var/spool/asterisk/monitor

  rtpengine:
    image: ${OMLRTPENGINE_IMG}
    container_name: oml-rtpengine
    networks:
      omnileads:
        ipv4_address: ${RTPENGINE_CONTAINER_IPV4}
    environment:
      - ENV=nat
      - TZ=${TZ}
      - PUBLIC_IP=${PUBLIC_IP}
      - RTPENGINE_HOSTNAME=${RTPENGINE_CONTAINER_IPV4}
    privileged: true
    restart: on-failure
    stop_grace_period: 10s
    # command: rtpengine --config-file /etc/rtpengine.conf   
    # volumes:
    #   - ../.custom_conf/rtpengine.conf:/etc/rtpengine.conf:ro

  websockets:
    tty: true
    container_name: oml-websockets
    image: ${OMLWS_IMG}
    depends_on:
      - redis
    environment:
      - BIND_ADDRESS=0.0.0.0:8000
      - EVENT_LOOP=uvloop
      - LOGGERS=${WEBSOCKET_LOGGER}
      - REDIS_HOST=${WEBSOCKET_REDIS_HOSTNAME}
      - PYTHONUNBUFFERED=1
    networks:
      - omnileads
    stop_grace_period: 30s  

  redis:
    container_name: oml-redis
    image: ${OMLREDIS_IMG}
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - BIND_IP=0.0.0.0
    networks:
      - omnileads    
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - redis:/data
      
  rabbitmq:
    container_name: oml-rabbit-mq
    image: rabbitmq:management
    networks:
      - omnileads
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  omnileads:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}"

volumes:
  redis:
  django_static:
  django_callrec_zip:
  asterisk_callrec:
  asterisk_sounds:
  asterisk_conf:
