# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can nginxtribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

- name: HAPROXY installation and configuration
  hosts: omnileads_haproxy
  tags:
    - haproxy
  vars:
    img_repo: '{{ container_image_registry }}/haproxy'
  tasks:

    - name: HAPROXY environment variables for this installation
      template:
        src: "{{ haproxy_repo_path }}templates/haproxy.env"
        dest: /etc/default/haproxy.env
        mode: 664
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
      tags:
        - install
        - upgrade

    - name: HAPROXY Copy haproxy.service Systemd file
      template:
        src: "{{ haproxy_repo_path }}templates/haproxy.service"
        dest: /etc/systemd/system/haproxy.service
      tags:
        - install
        - upgrade

    - name: HAPROXY Copy haproxy.cfg config file
      template:
        src: "{{ haproxy_repo_path }}templates/haproxy.cfg"
        dest: /etc/omnileads
      tags:
        - install
        - upgrade

    - name: Copy ssl cert
      copy:
        src: "{{ haproxy_repo_path }}certs/hap.pem"
        dest: /etc/omnileads
        mode: '0400'
      tags:
        - install
        - upgrade
  
      #when: certs == "selfsigned"

    - name: HAPROXY Pull image
      command: "podman pull --quiet {{ img_repo }}:{{ haproxy_version }}"
      register: podman_pull
      until: podman_pull is success
      tags:
        - install
        - upgrade

    - name: HAPROXY Enable and start service
      systemd:
        name: haproxy.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags:
        - install
        - upgrade
