# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

---

- name: RTPENGINE installation and configuration
  hosts: 
    - omnileads_voice
    - omnileads_aio
  tags:
    - all_components
    - voice
    - rtpengine
  vars:
    img_repo: '{{ img_registry_core_url }}/{{ img_registry_core_repo }}/rtpengine'
  tasks:

  - name: RTPENGINE Set environment variables
    template:
      src: "{{ rtpengine_repo_path }}templates/rtpengine.env"
      dest: /etc/default/rtpengine.env
      mode: 644
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - install
      - upgrade
      - update

  - name: RTPENGINE Copy Systemd .service file
    template:
      src: "{{ rtpengine_repo_path }}templates/rtpengine.service"
      dest: /etc/systemd/system/rtpengine.service
    tags:
      - install
      - upgrade
      - update

  - name: RTPENGINE Pull image
    command: podman pull --quiet {{ img_repo }}:{{ rtpengine_version }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update

  - name: RTPENGINE Enable and start service
    systemd:
      name: rtpengine.service
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
      - install

  - name: RTPENGINE Rstart service
    systemd:
      name: rtpengine.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade
      - restart
      - restart_rtpengine
    when:       
      - inventory_hostname in groups['omnileads_voice'] or inventory_hostname in groups['omnileads_aio']      