services:

  prometheus:
    image: prom/prometheus:${prometheus_img_tag}
    container_name: oml-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - oml_omnileads
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./prometheus.yml/:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  nodeexporter:
    image: prom/node-exporter:${prometheus_node_exporter_img_tag}
    container_name: oml-nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - oml_omnileads
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: "50m"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: oml-cadvisor
    networks:
      - oml_omnileads
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: oml-redis-exp
    networks:
      - oml_omnileads
    restart: unless-stopped
    environment:
      - REDIS_ADDR=${REDIS_HOSTNAME}:6379
      - REDIS_USER=null
      - REDIS_PASSWORD=null

volumes:
  prometheus_data:

networks:
  oml_omnileads:
    external: true
