# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can nginxtribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

- name: KAMAILIO Kamailio installation and configuration
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - all_components
    - kamailio
    - app
  vars:
    img_repo: '{{ container_image_registry }}/omnileads/kamailio'
  tasks:

    - name: KAMAILIO environment variables for this installation
      template:
        src: "{{ kamailio_repo_path }}templates/kamailio.env"
        dest: /etc/default/kamailio.env
        mode: 664
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
      tags:
        - install
        - upgrade

    - name: KAMAILIO Copy kamailio.service Systemd file
      template:
        src: "{{ kamailio_repo_path }}templates/kamailio.service"
        dest: /etc/systemd/system/kamailio.service
      tags:
        - install
        - upgrade

    # - name: KAMAILIO Copy kamailio.cfg Systemd file
    #   template:
    #     src: "{{ kamailio_repo_path }}templates/kamailio.cfg"
    #     dest: /etc/omnileads/kamailio.cfg
    #     mode: 664
    #     owner: "{{ usuario }}"
    #     group: "{{ usuario }}"
    #   tags:
    #     - install
    #     - upgrade
    #   when: omnileads_ha is defined

    - name: KAMAILIO Pull image
      command: podman pull --quiet {{ img_repo }}:{{ kamailio_version }}
      register: podman_pull
      until: podman_pull is success
      tags:
        - install
        - upgrade

    - name: KAMAILIO Enable and start service
      systemd:
        name: kamailio.service
        state: started
        enabled: yes
        daemon_reload: yes
      tags:
        - install
        - upgrade

    - name: KAMAILIO ReStart service
      systemd:
        name: kamailio.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags:
        - restart
