global:
  scrape_interval:     10s
  evaluation_interval: 10s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: '{{ tenant_id }}_host'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: '{{ tenant_id }}_redis'
    static_configs:
      - targets: ['localhost:9121']

  - job_name: '{{ tenant_id }}_asterisk'
    static_configs:
      - targets: ['localhost:7088']

  - job_name: '{{ tenant_id }}_cadvisor'
    static_configs:
      - targets: ['localhost:8080']