global:
  scrape_interval:     10s
  evaluation_interval: 10s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: '{{ tenant_folder }}_host'
    static_configs:
      - targets: ['localhost:9100']

  # - job_name: '{{ tenant_folder }}_heplify-server'
  #   static_configs:
  #     - targets: ['localhost:9096']

# {% if postgres_out != true %}
#   - job_name: '{{ tenant_folder }}_postgres'
#     static_configs:
#       - targets: ['localhost:9187']
# {% endif %}

  - job_name: '{{ tenant_folder }}_redis'
    static_configs:
      - targets: ['localhost:9121']

  - job_name: '{{ tenant_folder }}_asterisk'
    static_configs:
      - targets: ['localhost:7088']

  - job_name: '{{ tenant_folder }}_cadvisor'
    static_configs:
      - targets: ['localhost:8080']