#!/bin/bash

  case $1 in
  --reset_all)
    echo "WARNING reset all omnileadd Stack !!!!! "
    file_date=$2
    echo "¿ATTENTION: Are you sure you want to delete all OMniLeads DATA ???"
    read confirmacion
    docker-compose down
    docker volume rm postgresql redis minio django django_callrec_zip mariadb
    docker-compose up -d
    until curl -sk --head  --request GET https://localhost |grep "302" > /dev/null; do echo "Environment still initializing , sleeping 10 seconds"; sleep 10; done; echo "Environment is up"
    docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py cambiar_admin_password
    ;;
  --reset_pass)
    echo "reset django admin password"
    docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py cambiar_admin_password
    ;;
  --init_env)
    docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py inicializar_entorno
    ;;
  --call_generate)
    echo "generate an ibound call through PSTN-Emulator container"
    #docker exec -it oml-pstn-emulator sipp -sn uac 127.0.0.1:5060 -s stress -m 1 -r 1 -d 60000 -l 1
    docker exec -it oml-pstn-emulator sipp -sn uac 127.0.0.1:5070 -s stress -m $2 -r $3 -rp 50 -d 60000
    ;;
  --call_generate_did)
    echo "generate an ibound call through PSTN-Emulator container to DID: $2"
    docker exec -it oml-pstn-emulator sipp -sn uac 127.0.0.1:5070 -s $2 -m 1 -r 1 -d 60000 -l 1
    ;;  
  --backup)
    file_date=$(date +'%y%m%d.%H%M')
    docker run --network=host --env-file .env -e POSTGRES_BACKUP=True -e BACKUP_FILENAME=pgsql-backup-$file_date.sql omnileads/omlapp:231005.01 /opt/omnileads/bin/init_pgsql_backup.sh
    docker exec -it oml-asterisk /opt/asterisk/scripts/asterisk_backup.py $file_date
    ;;
  --restore)
    file_date=$2
    echo "¿Are you sure you want to delete the database & restore backup DB? yes or no"
    read confirmacion
    if [[ $confirmacion == "yes" ]]; then
      echo "echo drop all on PostgreSQL"
      docker stop oml-postgres
      docker rm oml-postgres
      docker volume rm oml_postgresql_data
      docker-compose -f docker-compose_prod_external_bucket.yml up -d
      until curl -sk --head  --request GET https://localhost |grep "302" > /dev/null; do echo "Environment still initializing , sleeping 10 seconds"; sleep 10; done; echo "Environment is up"
      docker run --network=host -e POSTGRES_RESTORE=True -e BACKUP_FILENAME=pgsql-backup-$file_date.sql --env-file .env omnileads/omlapp:1.30.0
      docker exec -it oml-asterisk python /opt/asterisk/scripts/asterisk_restore.py $file_date
      docker exec -it oml-asterisk asterisk -rx 'dialplan reload'
    else
      echo "Operación cancelada."
    fi  
    ;;
  --postgres_drop_db)
    echo "¿Are you sure you want to delete the database? yes or no"
    read confirmacion
    if [[ $confirmacion == "yes" ]]; then
      echo "echo drop all on PostgreSQL"
      docker stop oml-nginx
      docker stop oml-uwsgi
      docker stop oml-uwsgi-cron
      docker stop oml-asterisk
      docker stop oml-fastagi
      docker stop oml-postgres
      docker rm oml-postgres
      docker volume rm oml_postgresql_data
      docker-compose up -d 
      until curl -sk --head  --request GET https://localhost |grep "302" > /dev/null; do echo "Environment still initializing , sleeping 10 seconds"; sleep 10; done; echo "Environment is up"
      docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py cambiar_admin_password
    else
      echo "Operación cancelada."
    fi
    ;;
  --postgres_clean_tables)
    echo "¿Are you sure you want to delete the database? yes or no"
    read confirmacion
    if [[ $confirmacion == "yes" ]]; then
      echo "drop calls and agent count tables PostgreSQL"
      docker exec -it oml-uwsgi psql -c 'DELETE FROM queue_log'
      docker exec -it oml-uwsgi psql -c 'DELETE FROM reportes_app_llamadalog'
      docker exec -it oml-uwsgi psql -c 'DELETE FROM reportes_app_actividadagentelog'
      docker exec -it oml-uwsgi psql -c 'DELETE FROM ominicontacto_app_respuestaformulariogestion'
      docker exec -it oml-uwsgi psql -c 'DELETE FROM ominicontacto_app_auditoriacalificacion'
      docker exec -it oml-uwsgi psql -c 'DELETE FROM ominicontacto_app_calificacioncliente'
    else
      echo "Operación cancelada."
    fi
    ;;
  --postgres_psql)
    docker exec -it oml-uwsgi psql
    ;;      
  --redis_clean)
    echo "¿Are you sure you want to delete all redis cache? yes or no"
    read confirmacion
    if [[ $confirmacion == "yes" ]]; then
      docker exec -it oml-redis redis-cli flushall
    else
      echo "Cancel action"
    fi
    ;;  
   --redis_sync)
    docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py regenerar_asterisk
    ;;
  --redis_cli)
    docker exec -it oml-redis redis-cli
    ;;  
  --dialer_sync)
    docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py regenerar_asterisk
    ;; 
  --bucket_show)
    mc alias set MINIO http://localhost:9000 minio s3minio123
    mc ls --recursive MINIO/omnileads
    ;;
  --asterisk_cli)
    docker exec -it oml-asterisk asterisk -rvvvv
    ;;
  --asterisk_bash)
    docker exec -it oml-asterisk bash
    ;;
  --asterisk_logs)
    docker logs -f oml-asterisk
    ;;
  --kamailio_logs)
    docker logs -f oml-kamailio
    ;;
  --django_logs)
    docker logs -f oml-uwsgi
    ;;
  --django_bash)
    docker exec -it oml-uwsgi bash
    ;;  
  --django_shell)
    docker exec -it oml-uwsgi python3 manage.py shell
    ;;    
  --django_commands)
    REPO=$(cat .env | grep REPO= | awk -F'=' '{print $2}')
    docker exec -it oml-uwsgi /opt/omnileads/bin/django_commands.sh
    ;;      
  --fastagi_bash)
    docker exec -it oml-fastagi bash
    ;;      
  --fastagi_logs)
    docker logs -f oml-fastagi
    ;;
  --astami_logs)
    docker logs -f oml-fastagi
    ;;  
  --rtpengine_logs)
    docker logs -f oml-rtpengine
    ;;
  --rtpengine_bash)
    docker exec -it oml-rtpengine bash
    ;;  
  --websockets_logs)
    docker logs -f oml-websockets
    ;;
  --rtpengine_conf)
    docker exec -it oml-rtpengine cat /etc/rtpengine.conf
    ;;
  --nginx_t)
    docker exec -it oml-nginx nginx -T
    ;;
  --nginx_bash)
    docker exec -it oml-nginx bash
    ;;  
  --nginx_logs)
    docker logs -f oml-nginx
    ;;    
  --dialer_sync)
    docker exec -it oml-uwsgi python3 /opt/omnileads/ominicontacto/manage.py sincronizar_wombat
    ;;      

  --help)
    echo "
NAME:
OMniLeads docker-compose cmd tool

USAGE:
./manage.sh COMMAND

--reset_pass: reset admin password to admin admin
--init_env: init some basic configs in order to test it
--call_generate: generate an ibound call through PSTN-Emulator container. Arg1: calls  Arg2: caps [optional] Arg3 tel num.
--backup: take a postgres & asterisk backup and send to external bucket
--postgres_drop_db: delete all PostgreSQL databases
--postgres_clean_logs: drop calls and agent count tables PostgreSQL 
--redis_clean: clean App redis cache
--redis_sync: sync django & redis
--redis_cli: launch redis cli
--asterisk_cli: launch asterisk CLI
--asterisk_bash: launch asterisk container bash shell
--asterisk_logs: show asterisk container logs
--kamailio_logs: show container logs
--django_logs: show container logs
--django_bash: launch django container bash promt
--django_shell: launch django shell 
--django_commands: run migrations and others django_commands
--rtpengine_logs: show container logs
--websockets_logs: show container logs
--nginx_t: print nginx container run config
--nginx_logs_access
--nginx_logs_error
"
    shift
    exit 1
    ;;
  *)
    echo "ERROR oml_action var is unset";
    exit 1
    ;;
esac
