# qa_repoCopyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

---

- name: REDIS OMniLeads Redis component deploy
  hosts: 
    - omnileads_data
    - omnileads_aio
  tags:
    - all_components
    - redis
    - install
  tasks:

  - name: REDIS Set Redis environment variables for this installation
    template:
      src: "{{ redis_repo_path }}templates/redis.env"
      dest: /etc/default/redis.env
      mode: 664
      owner: '{{ usuario }}'
      group: '{{ usuario }}'
    tags:
      - upgrade

  - name: REDIS Copy systemd service
    template:
      src: "{{ redis_repo_path }}templates/redis.service"
      dest: /etc/systemd/system/redis.service
    tags:
      - upgrade
      - update

  - name: REDIS Pull image
    command: podman pull --quiet {{ redis_img }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - upgrade
      - update
    when: omnileads_ha is not defined   

  - name: REDIS Enable and start service
    systemd:
      name: redis.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade

  - name: REDIS Restart service
    systemd:
      name: redis.service
      state: restarted
      daemon_reload: yes
    tags:
      - upgrade
      - restart
    when:       
      - inventory_hostname in groups['omnileads_data'] or inventory_hostname in groups['omnileads_aio']    
############################## PROMETHEUS ###################################
  - name: REDIS prometheus Set environment variables for this installation
    template:
      src: "{{ redis_repo_path }}templates/prometheus.env"
      dest: /etc/default/prometheus_redis.env
      mode: 664
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - observability
      - upgrade
      - update

  - name: REDIS prometheus Copy systemd file
    template:
      src: "{{ redis_repo_path }}templates/prometheus.service"
      dest: /etc/systemd/system/prometheus_redis.service
    tags:
      - observability
      - upgrade
      - update

  - name: REDIS prometheus Pull image
    command: podman pull --quiet {{ redis_prometheus_img }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - observability
      - upgrade

  - name: REDIS prometheus Enable and start service
    systemd:
      name: prometheus_redis.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - observability
      - upgrade
