# qa_repoCopyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: INTERACTION_PROCESSOR OMniLeads application installation
  hosts: 
    - omnileads_voice
    - omnileads_aio
  tags:
    - interaction_processor
  vars:

  tasks:

  - name: INTERACTION_PROCESSOR environment variables
    template:
      src: "{{ interaction_processor_repo_path }}templates/interaction_processor.env"
      dest: /etc/default/interaction_processor.env
      mode: 666
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - install
      - upgrade
      - update

  - name: INTERACTION_PROCESSOR Copy systemd service file
    template:
      src: "{{ interaction_processor_repo_path }}templates/interaction_processor.service"
      dest: /etc/systemd/system/interaction_processor.service
    tags:
      - install
      - upgrade
      - update

  - name: INTERACTION_PROCESSOR Pull image
    command: podman pull --quiet {{ interaction_processor_img }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update

  - name: INTERACTION_PROCESSOR Enable and start systemd service
    systemd:
      name: interaction_processor.service
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade

  - name: INTERACTION_PROCESSOR ReStart systemd service
    systemd:
      name: interaction_processor.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade
      - restart
      - restart_interaction_processor
      - restart_core
    when:       
      - inventory_hostname in groups['omnileads_voice'] or inventory_hostname in groups['omnileads_aio']  