global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:  

{% if inventory_hostname in groups['omnileads_aio'] %}

{% if omnileads_ha is defined %}

  - job_name: '{{ tenant_id }}_host'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'ha'
          component: 'aio_os'

  - job_name: '{{ tenant_id }}_redis'
    static_configs:
      - targets: ['{{ omni_ip_lan }}:9121']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'ha'
          component: 'redis'

  - job_name: '{{ tenant_id }}_asterisk'
    static_configs:
      - targets: ['localhost:7088']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'ha'
          component: 'asterisk'

  - job_name: '{{ tenant_id }}_postgres_main_host'
    static_configs:
      - targets: ['{{ postgres_1 }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'ha'
          component: 'postgres_ha_1'

  - job_name: '{{ tenant_id }}_postgres_backup_host'
    static_configs:
      - targets: ['{{ postgres_2 }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'ha'
          component: 'postgres_ha_2'        

{% else %}

  - job_name: '{{ tenant_id }}_host'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'aio_os'

  - job_name: '{{ tenant_id }}_redis'
    static_configs:
      - targets: ['{{ omni_ip_lan }}:9121']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'redis'

  - job_name: '{{ tenant_id }}_asterisk'
    static_configs:
      - targets: ['localhost:7088']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'asterisk'

  - job_name: '{{ tenant_id }}_postgres'
    static_configs:
      - targets: ['{{ omni_ip_lan }}:9187']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'postgres'  

  - job_name: '{{ tenant_id }}_podman'
    static_configs:
      - targets: ['{{ omni_ip_lan }}:9882']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'podman'

{% endif %}

{% else %}

  - job_name: '{{ tenant_id }}_postgres'
    static_configs:
      - targets: ['{{ data_host }}:9187']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'postgres'
  
  - job_name: '{{ tenant_id }}_app_host'
    static_configs:
      - targets: ['{{ application_host }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'os_app'

  - job_name: '{{ tenant_id }}_voice_host'
    static_configs:
      - targets: ['{{ voice_host }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'os_voice'

  - job_name: '{{ tenant_id }}_data_host'
    static_configs:
      - targets: ['{{ data_host }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'os_data'

  - job_name: '{{ tenant_id }}_app_podman'
    static_configs:
      - targets: ['{{ application_host }}:9882']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'podman_app'

  - job_name: '{{ tenant_id }}_voice_podman'
    static_configs:
      - targets: ['{{ voice_host }}:9882']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'podman_voice'

  - job_name: '{{ tenant_id }}_data_podman'
    static_configs:
      - targets: ['{{ data_host }}:9882']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'podman_data'

  - job_name: '{{ tenant_id }}_redis'
    static_configs:
      - targets: ['{{ data_host }}:9121']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'redis'

  - job_name: '{{ tenant_id }}_asterisk'
    static_configs:
      - targets: ['{{ voice_host }}:7088']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'asterisk'

{% endif %}
