server:
  http_listen_port: 9080
  http_listen_address: {{ omni_ip_lan }}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ loki_host }}:3100/loki/api/v1/push

scrape_configs:

{% if inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio'] %}
- job_name: uwsgi
  static_configs:
  - targets:
      - localhost
    labels:
      job: uwsgi
      __path__: /var/lib/containers/storage/volumes/django_logs/_data/*.log
      env: production
      component: uwsgi
      tenant: {{ tenant_id }}

- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/lib/containers/storage/volumes/nginx_logs/_data/*.log
      env: production
      component: nginx
      tenant: {{ tenant_id }}

# - job_name: app_syslog
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: app_syslog
#       __path__: /var/log/omlapp/syslog

{% elif inventory_hostname in groups['omnileads_voice'] or inventory_hostname in groups['omnileads_aio'] %}
- job_name: asterisk_full
  static_configs:
  - targets:
      - localhost
    labels:
      job: asterisk
      __path__: /var/lib/containers/storage/volumes/asterisk_logs/_data/full
      env: production
      component: asterisk
      tenant: {{ tenant_id }}

- job_name: asterisk_conf_provisioner
  static_configs:
  - targets:
      - localhost
    labels:
      job: asterisk
      __path__: /var/lib/containers/storage/volumes/asterisk_logs/_data/websockets.log
      env: production
      component: asterisk
      tenant: {{ tenant_id }}

# - job_name: rtpengine
#   static_configs:
  # - targets:
  #     - localhost
  #   labels:
  #     job: rtpengine
  #     __path__: /var/log/rtpengine.log

# - job_name: voice_syslog
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: voice_syslog
#       __path__: /var/log/omlvoice/syslog

{% elif inventory_hostname in groups['omnileads_data'] or inventory_hostname in groups['omnileads_aio'] %}
# - job_name: postgres
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: postgres
#       __path__: /var/log/postgres.log

# - job_name: redis
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: redis
#       __path__: /var/log/redis.log

- job_name: data_syslog
  static_configs:
  - targets:
      - localhost
    labels:
      job: data_syslog
      __path__: /var/log/omldata/syslog
      component: asterisk
      tenant: {{ tenant_id }}

{% else %}
{% endif %}     