global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:  

{% if inventory_hostname in groups['omnileads_aio'] %}

  - job_name: '{{ tenant_id }}_host'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'aio_os'

  - job_name: '{{ tenant_id }}_redis'
    static_configs:
      - targets: ['localhost:9121']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'redis'

  - job_name: '{{ tenant_id }}_asterisk'
    static_configs:
      - targets: ['localhost:7088']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'aio'
          component: 'asterisk'

{% else %}

  - job_name: '{{ tenant_id }}_postgres'
    static_configs:
      - targets: ['{{ data_host }}:9187']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'postgres'
  
  - job_name: '{{ tenant_id }}_app_host'
    static_configs:
      - targets: ['{{ application_host }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'os_app'

  - job_name: '{{ tenant_id }}_voice_host'
    static_configs:
      - targets: ['{{ voice_host }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'os_voice'

  - job_name: '{{ tenant_id }}_data_host'
    static_configs:
      - targets: ['{{ data_host }}:9100']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'os_data'

  - job_name: '{{ tenant_id }}_redis'
    static_configs:
      - targets: ['{{ data_host }}:9121']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'redis'

  - job_name: '{{ tenant_id }}_asterisk'
    static_configs:
      - targets: ['{{ voice_host }}:7088']
        labels:
          tenant: '{{ tenant_id }}'
          arq: 'cluster'
          component: 'asterisk'

{% endif %}
