server:
  http_listen_port: 9080
  http_listen_address: {{ omni_ip_lan }}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ loki_host }}:3100/loki/api/v1/push

scrape_configs:

{% if inventory_hostname in groups['omnileads_app'] %}
  - job_name: uwsgi
    static_configs:
    - targets:
        - localhost
      labels:
        job: uwsgi        
        env: production
        component: uwsgi
        tenant: {{ tenant_id }}
        __path__: /var/lib/containers/storage/volumes/django_logs/_data/django.log

  - job_name: nginx_access
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx        
        env: production
        component: nginx
        tenant: {{ tenant_id }}
        __path__: /var/lib/containers/storage/volumes/nginx_logs/_data/omnileads_access.log

  - job_name: nginx_error
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx        
        env: production
        component: nginx
        tenant: {{ tenant_id }}
        __path__: /var/lib/containers/storage/volumes/nginx_logs/_data/omnileads_error.log

{% elif inventory_hostname in groups['omnileads_voice'] %}
  - job_name: asterisk_full
    static_configs:
    - targets:
        - localhost
      labels:
        job: asterisk        
        env: production
        component: asterisk
        tenant: {{ tenant_id }}
        __path__: /var/lib/containers/storage/volumes/asterisk_logs/_data/full

  - job_name: asterisk_conf_provisioner
    static_configs:
    - targets:
        - localhost
      labels:
        job: asterisk        
        env: production
        component: asterisk
        tenant: {{ tenant_id }}
        __path__: /var/lib/containers/storage/volumes/asterisk_logs/_data/websockets.log

{% elif inventory_hostname in groups['omnileads_data'] %}


{% elif inventory_hostname in groups['omnileads_aio'] %}

- job_name: uwsgi
  static_configs:
  - targets:
      - localhost
    labels:
      job: uwsgi      
      env: production
      component: uwsgi
      tenant: {{ tenant_id }}
      __path__: /var/lib/containers/storage/volumes/django_logs/_data/django.log

- job_name: nginx_access
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx      
      env: production
      component: nginx
      tenant: {{ tenant_id }}
      __path__: /var/lib/containers/storage/volumes/nginx_logs/_data/omnileads_access.log

- job_name: nginx_error
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx      
      env: production
      component: nginx
      tenant: {{ tenant_id }}
      __path__: /var/lib/containers/storage/volumes/nginx_logs/_data/omnileads_error.log

- job_name: asterisk_full
  static_configs:
  - targets:
      - localhost
    labels:
      job: asterisk      
      env: production
      component: asterisk
      tenant: {{ tenant_id }}
      __path__: /var/lib/containers/storage/volumes/asterisk_logs/_data/full

- job_name: asterisk_conf_provisioner
  static_configs:
  - targets:
      - localhost
    labels:
      job: asterisk      
      env: production
      component: asterisk
      tenant: {{ tenant_id }}
      __path__: /var/lib/containers/storage/volumes/asterisk_logs/_data/websockets.log

{% else %}
{% endif %}     