global:
  scrape_interval:     10s
  evaluation_interval: 10s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  # - job_name: 'tenant_name_node_exporter'
  #   static_configs:
  #     - targets: ['nodeexporter:9100']

  # - job_name: 'tenant_name_postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  - job_name: 'tenant_name_redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'tenant_name_asterisk'
    static_configs:
      - targets: ['acd:7088']

  - job_name: 'tenant_name_cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']