# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: ASTERISK installation and configuration
  hosts: 
    - omnileads_voice
    - omnileads_aio
  tags:
    - install
    - voice
    - asterisk
  tasks:

  - name: ASTERISK Set environment variables for this installation
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "0664"
      owner: "omnileads"
      group: "omnileads"
    loop:
      - { src: "{{ asterisk_repo_path }}templates/asterisk.env", dest: "/etc/default/asterisk.env" }
      - { src: "{{ asterisk_repo_path }}templates/asterisk_retrieve_conf.env", dest: "/etc/default/asterisk_retrieve_conf.env" }
    tags:
      - install
      - upgrade
      - update

  - name: ASTERISK Copy systemd services
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: "{{ asterisk_repo_path }}templates/asterisk.service", dest: "/etc/systemd/system/asterisk.service" }
      - { src: "{{ asterisk_repo_path }}templates/asterisk_retrieve_conf.service", dest: "/etc/systemd/system/asterisk_retrieve_conf.service" }
    tags:
      - install
      - upgrade
      - update

  - name: Pull Asterisk images
    command: podman pull --quiet {{ item.image }}
    register: podman_pull_result
    until: podman_pull_result is success
    loop:
      - { image: "{{ asterisk_img }}" }
      - { image: "{{ asterisk_retrieve_conf_img }}" }
    tags:
      - install
      - upgrade
      - update

  - name: ASTERISK Enable and start systemd services
    systemd:
      name: "{{ item.name }}"
      state: started
      enabled: yes
      daemon_reload: yes
    loop:
      - { name: 'asterisk_retrieve_conf.service' }
      - { name: 'asterisk.service' }
    when: omnileads_ha is not defined
    tags:
      - install
      - upgrade

  - name: ASTERISK Start systemd services on HA scenary
    systemd:
      name: "{{ item.name }}"
      state: started
      enabled: no
      daemon_reload: yes
    loop:
      - { name: 'asterisk_retrieve_conf.service' }
      - { name: 'asterisk.service' }
    when: 
      - omnileads_ha is defined
      - ha_role == 'main'
    tags:
      - install
      - upgrade

  - name: ASTERISK Restart systemd services
    systemd:
      name: "{{ item.name }}"
      state: restarted
      enabled: yes
      daemon_reload: yes
    loop:
      - { name: 'asterisk.service' }
      - { name: 'asterisk_retrieve_conf.service' }
    tags:
      - upgrade
      - restart
      - restart_core
      - restart_asterisk
    when: 
      - omnileads_ha is not defined