# qa_repoCopyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: ASTERISK installation and configuration
  hosts: 
    - omnileads_voice
    - omnileads_aio
  tags:
    - install
    - voice
    - asterisk
  vars:
    img_repo: '{{ img_registry_omlacd_url }}/{{ img_registry_omlacd_repo }}/asterisk'
  tasks:

  - name: ASTERISK Set environment variables for this installation
    template:
      src: "{{ asterisk_repo_path }}templates/asterisk.env"
      dest: /etc/default/asterisk.env
      mode: 664
      owner: '{{ usuario }}'
      group: '{{ usuario }}'
    tags:
      - install
      - upgrade
      - update

  - name: ASTERISK Copy systemd service
    template:
      src: "{{ asterisk_repo_path }}templates/asterisk.service"
      dest: /etc/systemd/system/asterisk.service
    tags:
      - install
      - upgrade
      - update

  - name: ASTERISK Pull image
    command: podman pull --quiet {{ img_repo }}:{{ asterisk_version }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update

  - name: ASTERISK Enable and start systemd service
    systemd:
      name: asterisk.service
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade
    
  - name: ASTERISK Restart systemd service
    systemd:
      name: asterisk.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade
      - restart
      - restart_core
    when:       
        - inventory_hostname in groups['omnileads_voice'] or inventory_hostname in groups['omnileads_aio']  
