global:
  scrape_interval:     10s
  evaluation_interval: 10s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'tenant_name_node_exporter'
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          tenant: 'docker-compose'
          arq: 'docker-desktop'
          component: 'host-docker'

  - job_name: 'tenant_name_redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          tenant: 'docker-compose'
          arq: 'docker-desktop'
          component: 'redis'

  - job_name: 'tenant_name_asterisk'
    static_configs:
      - targets: ['acd:7088']
        labels:
          tenant: 'docker-compose'
          arq: 'docker-desktop'
          component: 'asterisk'

  - job_name: 'tenant_name_cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          tenant: 'docker-compose'
          arq: 'docker-desktop'
          component: 'cadvisor'