# qa_repoCopyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: ADDONS OMniLeads application installation
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - addons
  vars:    
    INSTALL_PREFIX: "/opt/omnileads"

  tasks:

  - name: ADDON SURVEY from REDIS to Postgres Pull image
    command: podman pull --quiet {{ survey_worker_img }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update
    when: enterprise_edition == true

  - name: ADDON SURVEY Copy REDIS2POSTGRES systemd service
    template:
      src: "{{ addons_repo_path }}templates/survey_worker.service"
      dest: /etc/systemd/system/survey_worker.service
    tags:
      - install
      - upgrade
      - update
    when: enterprise_edition == true

  - name: ADDON SURVEY Redis2Postgres Enable and start systemd service
    systemd:
      name: survey_worker.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade
      - restart
    when: enterprise_edition == true    