# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
---
###############################################################################################################
##############################   The complete list of host  ################################################### 
###############################################################################################################
all:
  children:
    # -----------------------------------------
    # -----------------------------------------
    aio_instances:
      hosts:
        tenant_example_1:
          tenant_id: tenant_example_1
          ansible_host: 190.19.150.18
          omni_ip_lan: 172.16.101.44
        tenant_example_2:
          tenant_id: tenant_example_2
          ansible_host: 190.19.11.2
          omni_ip_lan: 10.10.10.2          
          infra_env: lan
          ansible_ssh_port: 2234
        tenant_example_nat:
          tenant_id: tenant_example_nat
          ansible_host: 190.19.11.2
          omni_ip_lan: 10.10.10.2          
          infra_env: nat
          ansible_ssh_port: 2237
          nat_ip_addr: 190.19.11.2
        tenant_example_3:
          tenant_id: tenant_example_3
          ansible_host: 201.22.11.2
          omni_ip_lan: 10.10.10.3
          postgres_host: 10.10.10.4     
          postgres_port: 25080
          postgres_user: something_different
          postgres_password: fadshjfadsjfhjkwh43
          postgres_database: omnileads
          postgres_maintenance_db: defaultdb
          postgres_ssl: true
          bucket_access_key: something_different
          bucket_secret_key: kljdaklsjklKJHKL786786KJHJKH
          bucket_name: tenant_example_3
        tenant_example_4:          
          tenant_id: tenant_example_4
          ansible_host: 172.16.101.109
          omni_ip_lan: 172.16.101.109
          infra_env: lan 
          qa_env: true
          ansible_ssh_port: 2234
    # -----------------------------------------
    # -----------------------------------------
    cluster_instances:
      children:
        tenant_example_5:
          hosts:
            tenant_example_5_data:
              ansible_host: 172.16.101.41
              omni_ip_lan: 172.16.101.41
              ansible_ssh_port: 22
            tenant_example_5_voice:
              ansible_host: 172.16.101.42
              omni_ip_lan: 172.16.101.42
              ansible_ssh_port: 22
            tenant_example_5_app:
              ansible_host: 172.16.101.43
              omni_ip_lan: 172.16.101.43
              ansible_ssh_port: 22
          vars:
            tenant_id: tenant_example_5
            data_host: 172.16.101.41
            voice_host: 172.16.101.42
            application_host: 172.16.101.43
            infra_env: lan
        tenant_example_6:
          hosts:
            tenant_example_6_data:
              ansible_host: 179.34.22.11
              omni_ip_lan: 192.168.0.2
            tenant_example_6_voice:
              ansible_host: 179.134.12.18
              omni_ip_lan: 192.168.0.3
            tenant_example_6_app:
              ansible_host: 190.134.62.33
              omni_ip_lan: 192.168.0.4
          vars:
            tenant_id: tenant_example_6
            data_host: 192.168.0.2
            voice_host: 192.168.0.3
            application_host: 192.168.0.4
            infra_env: cloud
    # -----------------------------------------
    # -----------------------------------------              
    ha_instances:
      children:
        tenant_example_7:
          hosts:
            tenant_example_7_sql_A:
              tenant_id: tenant_example_7_sql_A
              ansible_host: 172.16.101.101
              omni_ip_lan: 172.16.101.101              
              ha_rol: main
            tenant_example_7_sql_B:
              tenant_id: tenant_example_7_sql_B
              ansible_host: 172.16.101.102
              omni_ip_lan: 172.16.101.102
              ha_rol: backup
            tenant_example_7_aio_A:
              tenant_id: tenant_example_7_aio_A
              ansible_host: 172.16.101.109
              omni_ip_lan: 172.16.101.109
              ha_rol: main
            tenant_example_7_aio_B:
              tenant_id: tenant_example_7_aio_B
              ansible_host: 172.16.101.110
              omni_ip_lan: 172.16.101.110
              ha_rol: backup              
          vars:            
            infra_env: lan
            omnileads_ha: true
            netaddr: 172.16.101.0/16
            netprefix: 16
            ha_vip_nic: ens18             
            postgres_1: 172.16.101.101
            postgres_2: 172.16.101.102
            aio_1: 172.16.101.109
            aio_2: 172.16.101.110
            omnileads_vip: 172.16.101.200
            postgres_rw_vip: 172.16.101.201
            postgres_ro_vip: 172.16.101.202
            bucket_url: https://172.16.101.3:9000
            bucket_access_key: mYLcr7sx5vEbe7PO
            bucket_secret_key: v1Dl34Q29Bv6ruaWS7cUAEvSVfAtvGkR
            bucket_name: tenant_example_7

##################################################################################################################
# -- OMniLeads Common Variables                                                                                  #
################################################################################################################## 
  vars:
    # --- ansible user auth connection
    ansible_user: root
    ansible_ssh_port: 22

    # ------------------------------------------------------------------------------------------------ #
    # ------------------------------ Generic OMniLeads runtime variables ----------------------------- #
    # ------------------------------------------------------------------------------------------------ #

    # --- Asterisk & RTPengine scenary for SIP & RTP
    # --- "cloud" instance (access through public IP)
    # --- "lan" instance (access through private IP)
    # --- "nat" instance (access through Public NAT IP)
    # --- "hybrid" instance (agent WebRTC through Public NAT IP, but PSTN acces through LAN VoIP GW)
    # --- or "all" in order to access through all NICs
    infra_env: cloud
    #nat_ip_addr: X.X.X.X
    # --- If you have an DNS FQDN resolution, you must to uncomment and set this param
    # --- otherwise leave commented to work invoking through an IP address
    #fqdn: fts.sefirot.cloud
    # --- If you want to work with Dialer, then you must install Wombat Dialer on a separate host 
    # --- and indicate the IP address or FQDN of that host here (uncomment and set this param):
    # --- time zone (for example: America/Argentina/Cordoba)
    TZ: America/Argentina/Cordoba
    # --- TLS/SSL Certs configuration (selfsigned, custom or certbot letsencrypt)
    # --- docs:
    # --- https://gitlab.com/omnileads/omldeploytool/-/blob/develop/ansible/README.md?ref_type=heads#tls-cert-provisioning
    certs: selfsigned
    notification_email: your_email@domain.com
    # --- PostgreSQL    
    postgres_port: 5432
    postgres_user: omnileads
    postgres_password: HJGKJHGDSAKJHK7856765DASDAS675765JHGJHSAjjhgjhaaa
    postgres_database: omnileads
    # --- *postgres* or *defaultdb* depend ...
    postgres_maintenance_db: postgres
    postgres_ssl: false
    postgres_utc: false
    # --- If you have a PGSQL cluster you can activated cluster mode
    # --- in order to split INSERT (RW node) & QUERIES (RO node)
    postgres_ha: false
    # --- OBJECT STORAGE
    # --- minio auth Web and Console admin params
    s3_http_admin_user: omnileads
    s3_http_admin_pass: jdhsgahkdgaskdasdhe2h4231hg4jjhgHJKG
    # --- bucket params    
    bucket_access_key: Hghjkdghjkdhasjdasdsada
    bucket_secret_key: jknkjhkjh4523kjhcksjdhkjfdhKJHHKJGKJh786876876NBVJHB
    bucket_name: omnileads
    #bucket_ssl_selfsigned: true
    # --- if your bucket doesn't need region, leave this value (us-east-1)
    bucket_region: us-east-1
    # --- Asterisk Manager Interface (AMI) user & password
    ami_user: omnileads
    ami_password: C12H17N2O4P_o98o98
    # --- Wombat Dialer API user & pass
    dialer_user: demoadmin
    dialer_password: demo
    # ---  kamailio shm & pkg memory params
    shm_size: 64
    pkg_size: 8
    # --- is the time in seconds that will last the https session when inactivity
    SCA: 3600
    # --- Ephemeral Credentials TTL (ECTTL) is the time in seconds            #
    # --- that will last the SIP credentials used to authenticate a SIP user  #
    # --- in the telephony system
    ECCTL: 28800
    # --- is the attempts a user has to enter an incorrect password in login
    LOGIN_FAILURE_LIMIT: 10
    # --- SMTP server params, if you want to use your own SMTP, put true and
    # --- uncomment all necesary
    email_smtp_relay: false
    #email_backend:
    #email_default_from:
    #email_host:
    #email_password:
    #email_user:
    #email_port:
    #email_ssl_certfile:
    #email_ssl_keyfile:
    #email_use_ssl:
    #email_use_tls:    
    
    # ------------------------------------------------------------------------------------------------ #
    # --------------------------------------- Integrations-------------------------------------------- #
    # ------------------------------------------------------------------------------------------------ #
    
    # --- Text to Speech external "gcp", "aws", "ibm", etc.
    #tts_external_engine: 
    # --- Speech analytics & sentiment analysis
    # --- "openai" or "gcp" (google cloud) or "local" (whisper for transcription & psysentiment for analysis)
    #speech_analytics_model: local
    # --- google maps integration credentials
    google_maps_api_key: NULL
    google_maps_center: '{ "lat": -31.416668, "lng": -64.183334 }'
    google_api_key: 
    google_cloud_projectid: 
    # --- openai integrations
    openai_api_key:
    # --- The Dialer Engine Host
    #dialer_host: 
    # --- set postgres_host if you have your own postgres (standalone host or cloud service)
    # --- otherwise leave commented to deploy PostgreSQL on Application Host instance
    #postgres_host:
    # --- Read Only connection host address (in case of RW/RO postgres cluster):
    #postgres_ro_vip: 
    # --- if you have your own bucket (standalone host or cloud service) put here the URL
    # --- example VULTR: https://ewr1.vultrobjects.com
    # --- example Digital Ocean: https://sfo3.digitaloceanspaces.com
    # --- example onpremise: https://192.168.100.10
    # --- if you want to deploy MinIO objects storage on application_host, you must to put '#' before
    #bucket_url: https://sfo3.digitaloceanspaces.com
    # --- RTPEngine if you have your own instances put here the IP or hostname
    #rtpengine_host: 
    # --- Observability integrations with Loki & Homer
    # --- Request by promtail:
    #loki_host:
    # --- Request by Asterisk hep module:
    #homer_host:
    # --- Request by Web-Video Inbound Calls 
    # --- Put here the JITSI host URL
    #video_host: 
    # --- Request by CRM integration callrec search & list API endpoint
    #CUSTOM_CORS_ALLOWED_ORIGINS=https://example1.net,https://example2.com,https://example3.tech
    
    # ------------------------------------------------------------------------------------------------ #
    # ------------------------------------ Scale tunnings -------------------------------------------- #
    # ------------------------------------------------------------------------------------------------ #
    swap_space: 1G
    #scale_uwsgi: true
    #processes: 8
    #threads: 1
    #scale_asterisk: true
    #asterisk_mem_limit: 1G
    #pjsip_threadpool_idle_timeout: 120
    #pjsip_threadpool_max_size: 150

    # ------------------------------------------------------------------------------------------------ #
    # ------------------------------------ Upgrade from OML 1.X -------------------------------------- #
    # ------------------------------------ Restore filename ------------------------------------------ #
    # ------------------------------------------------------------------------------------------------ #
    
    # --- Restore filename id, request by restore filename
    #restore_file_timestamp: 1681215859
    # Uncomment in case of upgrading from OML 1.X
    #upgrade_from_oml_1: true

    # ------------------------------------------------------------------------------------------------ #
    # ---------------------------- Container IMG TAG customization ----------------------------------- #
    # ------------------------------------------------------------------------------------------------ #
    # --- For each OML Deploy Tool release, a versioned stack with the latest stable images of each component is maintained on inventory.yml
    # --- You can combine the versions as you like, also use your own TAGs, using the following TAG version variables
    # --- If you want to deploy OMniLeads Enterprise, you just need to add "-enterprise" as a suffix to the omnileads_img image tag
    # --- for example: omnileads_img: docker.io/omnileads/omlapp:240216.01-enterprise.

    omnileads_img: docker.io/omnileads/omlapp:240513.01
    asterisk_img: docker.io/omnileads/asterisk:240503.01    

##############################################################################################################
## -- In this section the hosts are grouped based on the type of deployment (AIO, Cluster & Cluster HA).  -- #
## -- here you can control which host the action deployed by the deploy.sh script will be applied to      -- #
## -- The Ansible playbooks are applied on the hosts below declared and classified according to the       -- #
## -- architecture of the instance on which they are deployed.                                            -- #
##############################################################################################################

omnileads_aio:
  hosts:
    tenant_example_1:
    #tenant_example_2:
    #tenant_example_3:
    #tenant_example_4:
    #tenant_example_7_aio_A:
    #tenant_example_7_aio_B:
################################################    

omnileads_data:
  hosts:
    tenant_example_5_data:  
    
omnileads_voice:
  hosts:
    tenant_example_5_voice:

omnileads_app:
  hosts:
    tenant_example_5_app:

################################################

ha_omnileads_sql:
  hosts:
    #tenant_example_7_sql_A:
    #tenant_example_7_sql_B:
    
