---

all:
  hosts:
    omnileads-voice:
      omlvoice: true
      ansible_host: 172.16.101.41
      ansible_ssh_port: 22
      omni_ip_lan: 172.16.101.41
    omnileads-app:
      omlapp: true
      ansible_host: 172.16.101.42
      ansible_ssh_port: 22
      omni_ip_lan: 172.16.101.42
    omnileads-observability:
      omlobs: true
      ansible_host: 172.16.101.43
      ansible_ssh_port: 22
      omni_ip_lan: 172.16.101.43
  vars:
    # --- IP or hostname that each instance will invoke when locating the other
    voice_host: 172.16.101.41
    application_host: 172.16.101.42
    observability_host: 172.16.101.43
    # --- ansible user auth connection
    ansible_user: root
    # --- version of each image to deploy
    omnileads_version: RC-230204.01
    websockets_version: 230204.01
    nginx_version: 230204.01
    kamailio_version: 230204.01
    asterisk_version: 230204.01
    rtpengine_version: 230204.01
    postgres_version: 230204.01
    # --- "cloud" instance (access through public IP)
    # --- or "lan" instance (access through private IP)
    # --- in order to set NAT or Publica ADDR for RTP voice packages
    infra_env: lan
    # --- If you have an DNS FQDN resolution, you must to uncomment and set this param
    # --- otherwise leave commented to work invoking through an IP address
    #fqdn: fidelio.sephir.tech
    # --- time zone
    TZ: America/Argentina/Cordoba
    # --- TLS/SSL Certs configuration (selfsigned, custom or certbot letsencrypt)
    # --- if you have your own certs, put them into instances/tenant folder and
    # --- change this to *custom*
    certs: selfsigned
    # --- if you object storage service use selfsigned TLS/SSL certs, you mus to put
    # --- *callrec_device=s3-no-check-cert* in order to don't verify CA.
    callrec_device: s3
    # --- PostgreSQL
    # --- set postgres_host if you have your own postgres (standalone host or cloud service)
    # --- otherwise leave commented to deploy PostgreSQL on Application Host instance
    #postgres_host: vultr-prod-2e6af73c-76fc-4185-988a-37587f96b70a-vultr-prod-a539.vultrdb.com
    postgres_port: 5432
    postgres_user: omnileads
    postgres_password: AVNS_1VpA4nkIvuDy__Jfsdfdw
    postgres_database: omnileads
    # --- *postgres* or *defaultdb* depend ...
    postgres_maintenance_db: postgres
    postgres_ssl: false
    # --- If you have a PGSQL cluster you can activated cluster mode
    # --- in order to split INSERT (RW node) & QUERIES (RO node)
    postgres_ha: false
    # --- Read Only connection host address
    postgres_ro_host:
    # --- OBJECT STORAGE
    # --- if you have your own bucket (standalone host or cloud service) put here the URL
    # --- example VULTR: https://ewr1.vultrobjects.com
    # --- example Digital Ocean: https://sfo3.digitaloceanspaces.com
    # --- example onpremise: https://192.168.100.10
    # --- if you want to deploy MinIO objects storage on application_host, you must to put '#' before
    #bucket_url: https://172.16.101.3:9000
    # --- minio auth API params
    s3_http_admin_user: omnileads
    s3_http_admin_pass: 098098ZZZ
    # --- bucket params
    bucket_access_key: 9djhg3jkhghj32131
    bucket_secret_key: sZfsdfsdklfjdskjh3k2jh1kjh2kjh3kj1321
    bucket_name: ulver
    # --- if your bucket doesn't need region, leave this value (us-east-1)
    bucket_region: us-east-1
    # --- Asterisk Manager Interface (AMI) user & password
    ami_user: omnileads
    ami_password: C12H17N2O4P_o98o98
    # --- RTPEngine if you have your own instances put here the IP or hostname
    #rtpengine_host=
    # --- Wombat Dialer hostname/IP and API user / pass
    dialer_host: 10.10.10.4
    dialer_user: demoadmin
    dialer_password: 765765F1d3l10*
    # ---  kamailio shm & pkg memory params
    shm_size: 64
    pkg_size: 8
    # --- is the time in seconds that will last the https session when inactivity
    SCA: 3600
    # --- Ephemeral Credentials TTL (ECTTL) is the time in seconds            #
    # --- that will last the SIP credentials used to authenticate a SIP user  #
    # --- in the telephony system
    ECCTL: 28800
    # --- is the attempts a user has to enter an incorrect password in login
    LOGIN_FAILURE_LIMIT: 10
    google_maps_api_key: NULL
    google_maps_center: '{ "lat": -31.416668, "lng": -64.183334 }'
    # --- SMTP server params, if you want to use your own SMTP, put true and
    # --- uncomment all necesary
    email_smtp_relay: false
    #email_backend:
    #email_default_from:
    #email_host:
    #email_password:
    #email_user:
    #email_port:
    #email_ssl_certfile:
    #email_ssl_keyfile:
    #email_use_ssl:
    #email_use_tls:
