---

all:
  hosts:
    omnileads-voice:
      ansible_host: 172.16.101.13
      omni_ip_lan: 172.16.101.13
      application_host: 172.16.101.14
    omnileads-app:
      ansible_host: 172.16.101.14
      omni_ip_lan: 172.16.101.14
      voice_host: 172.16.101.13
      # ---  kamailio shm & pkg memory params
      shm_size: 64
      pkg_size: 8
      # --- is the time in seconds that will last the https session when inactivity
      SCA: 3600
      # --- Ephemeral Credentials TTL (ECTTL) is the time in seconds            #
      # --- that will last the SIP credentials used to authenticate a SIP user  #
      # --- in the telephony system
      ECCTL: 28800
      # --- is the attempts a user has to enter an incorrect password in login
      LOGIN_FAILURE_LIMIT: 10
      google_maps_api_key: NULL
      google_maps_center: '{ "lat": -31.416668, "lng": -64.183334 }'
      # --- SMTP server params, if you want to use your own SMTP, put true and
      # --- uncomment all necesary
      email_smtp_relay: false
      #email_backend:
      #email_default_from:
      #email_host:
      #email_password:
      #email_user:
      #email_port:
      #email_ssl_certfile:
      #email_ssl_keyfile:
      #email_use_ssl:
      #email_use_tls:
  vars:
    # --- version images to deploy
    django_version: latest
    websockets_version: latest
    nginx_version: latest
    kamailio_version: latest
    asterisk_version: latest
    rtpengine_version: latest
    # --- "cloud" instance (access through public IP)
    # --- or "lan" instance (access through private IP)
    infra_env: lan
    # --- ansible user & port connection
    ansible_ssh_port: 22
    ansible_user: root
    # --- time zone
    TZ: America/Argentina/Cordoba
    # ---  enable prometheus exporter redis & pgsql
    prometheus_enable: true
    # --- postgresl params
    # --- set postgres_host if you have your own postgres:
    #postgres_host: vultr-prod-2e6af73c-76fc-4185-988a-37587f96b70a-vultr-prod-a539.vultrdb.com
    # --- set true if you have an postgres isolate or cloud instance
    postgres_port: 5432
    postgres_user: omnileads
    postgres_password: AVNS_1VpA4nkIvuDy__Jfsdfdw
    postgres_database: omnileads
    postgres_maintenance_db: postgres #defaultdb
    postgres_ssl: false
    # --- If you have a PGSQL cluster you can activated cluster mode
    postgres_ha: false
    # --- Read Only connection host address
    postgres_ro_host:
    # --- if you have your own bucket put here the URL:
    # --- example VULTR: https://ewr1.vultrobjects.com
    # --- example Digital Ocean: https://sfo3.digitaloceanspaces.com
    # --- if you want to deploy minIO objects stporage on application_host, you must to put '#'
    # --- in order to comment bucket_url paramQue
    #bucket_url: https://ewr1.vultrobjects.com
    # --- minio auth API params
    s3_http_admin_user: omnileads
    s3_http_admin_pass: 098098ZZZ
    # --- bucket params
    bucket_access_key: 9dsffdsfsdfsd
    bucket_secret_key: sZfsdfsdklfjdslkfjgt543
    bucket_name: omnileads
    bucket_region: us-east-1
    # --- Asterisk AMI user & password
    ami_user: omnileads
    ami_password: C12H17N2O4P_o98o98
    # --- SIP HOMER capture activated
    homer_enable: true
    # --- Dialer API user & pass
    dialer_user: demoadmin
    dialer_password: demo
