# Copyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
---

###############################################################################################################
# -- The complete list of host                                                                                #
###############################################################################################################

all:
  children:
    cluster_ha_instances:
      children:
        tenant_aaa: 
          hosts:
            tenant_aaa_sql_1:
              ansible_host: 172.16.101.101
              omni_ip_lan: 172.16.101.101
              ansible_ssh_port: 22
              ha_vip_nic: eth0
            tenant_aaa_sql_2:
              ansible_host: 172.16.101.102
              omni_ip_lan: 172.16.101.102
              ansible_ssh_port: 22
              ha_vip_nic: eth0
            tenant_aaa_voice_1: 
              ansible_host: 172.16.101.103
              omni_ip_lan: 172.16.101.103
              ansible_ssh_port: 22
            tenant_aaa_voice_2: 
              ansible_host: 172.16.101.104
              omni_ip_lan: 172.16.101.104
              ansible_ssh_port: 22
            tenant_aaa_app_1:
              ansible_host: 172.16.101.105
              omni_ip_lan: 172.16.101.105
              ansible_ssh_port: 22
            tenant_aaa_app_2:
              ansible_host: 172.16.101.106
              omni_ip_lan: 172.16.101.106
              ansible_ssh_port: 22
            tenant_aaa_haproxy_1: 
              ansible_host: 172.16.101.107
              omni_ip_lan: 172.16.101.107
              ansible_ssh_port: 22
            tenant_aaa_haproxy_2: 
              ansible_host: 172.16.101.108
              omni_ip_lan: 172.16.101.108
              ansible_ssh_port: 22
          vars:
            tenant_id: tenant_aaa
            ### estas variables pueden ser optimizadas ###
            postgres_1: 172.16.101.101
            postgres_2: 172.16.101.102
            voice_1: 172.16.101.103
            voice_2: 172.16.101.104
            app_1: 172.16.101.105
            app_2: 172.16.101.106            
            haproxy_1: 172.16.101.107
            ##############################################
            ha_vip_nic: ens18
            app_port: 443
            # -- cluster info & virtual IPs
            redis_host: 172.16.101.204
            redis_ip_main: 172.16.101.105
            postgres_host: 172.16.101.201
            postgres_ro_host: 172.16.101.202
            voice_host: 172.16.101.203
            application_host: 172.16.101.204
            bucket_url: https://172.16.101.3:9000
            bucket_access_key: mYLcr7sx5vEbe7PO
            bucket_secret_key: v1Dl34Q29Bv6ruaWS7cUAEvSVfAtvGkR
            bucket_name: proxmox-deb

####################################### TALCA ########################################
####################################### TALCA ########################################
####################################### TALCA ########################################
####################################### TALCA ########################################
####################################### TALCA ########################################

        tenant_bbb: 
          hosts:
            tenant_bbb_sql_1:
              ansible_host: 172.16.101.111
              omni_ip_lan: 172.16.101.111
            tenant_bbb_sql_2:
              ansible_host: 172.16.101.112
              omni_ip_lan: 172.16.101.112
            tenant_bbb_voice_1: 
              ansible_host: 172.16.101.113
              omni_ip_lan: 172.16.101.113
            tenant_bbb_voice_2: 
              ansible_host: 172.16.101.114
              omni_ip_lan: 172.16.101.114
            tenant_bbb_app_1:
              ansible_host: 172.16.101.115
              omni_ip_lan: 172.16.101.115
            tenant_bbb_app_2:
              ansible_host: 172.16.101.116
              omni_ip_lan: 172.16.101.116
            tenant_bbb_haproxy_1: 
              ansible_host: 172.16.101.117
              omni_ip_lan: 172.16.101.117
            tenant_bbb_haproxy_2: 
              ansible_host: 172.16.101.118
              omni_ip_lan: 172.16.101.118              
          vars:
            tenant_id: tenant_bbb
            postgres_1: 172.16.101.101
            postgres_2: 172.16.101.102
            voice_1: 172.16.101.103
            voice_2: 172.16.101.104
            app_1: 172.16.101.105
            app_2: 172.16.101.106
            haproxy_1: 172.16.101.107
            ##############################################
            ha_vip_nic: ens18
            app_port: 443
            # -- cluster info & virtual IPs
            redis_host: 172.16.101.204
            redis_ip_main: 172.16.101.105
            postgres_host: 172.16.101.201
            postgres_ro_host: 172.16.101.202
            voice_host: 172.16.101.203
            application_host: 172.16.101.204
            bucket_url: https://172.16.101.3:9000
            bucket_access_key: mYLcr7sx5vEbe7PO
            bucket_secret_key: v1Dl34Q29Bv6ruaWS7cUAEvSVfAtvGkR
            bucket_name: tenant_bbb

##################################################################################################################
# -- OMniLeads Common Variables                                                                                  #
##################################################################################################################

  vars:    
    # --- ansible user auth connection
    ansible_user: root
    ansible_ssh_port: 22
    # --- Activate the OMniLeads Enterprise Edition - with "AAAA" licensed.
    # --- on the contrary you will deploy OMniLeads OSS Edition with GPLV3 licensed. 
    enterprise_edition: false
    # --- versions of each image to deploy
    # --- versions of each image to deploy
    omnileads_version: 1.28.0
    websockets_version: 230204.01
    nginx_version: 230215.01
    kamailio_version: 230204.01
    asterisk_version: 230604.01
    rtpengine_version: 230524.01
    postgres_version: 230204.01  
    centos_postgresql_version: 11
    # --- "cloud" instance (access through public IP)
    # --- or "lan" instance (access through private IP)
    # --- in order to set NAT or Publica ADDR for RTP voice packages
    infra_env: ha
    # --- If you have an DNS FQDN resolution, you must to uncomment and set this param
    # --- otherwise leave commented to work invoking through an IP address
    #fqdn: fts.sefirot.cloud
    # --- If you want to work with Dialer, then you must install Wombat Dialer on a separate host 
    # --- and indicate the IP address or FQDN of that host here (uncomment and set this param):
    #dialer_host: 
    # --- set postgres_host if you have your own postgres (standalone host or cloud service)
    # --- otherwise leave commented to deploy PostgreSQL on Application Host instance
    #postgres_host: 
    # --- Read Only connection host address (in case of RW/RO postgres cluster):
    #postgres_ro_host: 
    # --- if you have your own bucket (standalone host or cloud service) put here the URL
    # --- example VULTR: https://ewr1.vultrobjects.com
    # --- example Digital Ocean: https://sfo3.digitaloceanspaces.com
    # --- example onpremise: https://192.168.100.10
    # --- if you want to deploy MinIO objects storage on application_host, you must to put '#' before
    bucket_url: https://172.16.101.3:9000
    # --- RTPEngine if you have your own instances put here the IP or hostname
    #rtpengine_host: 
    # --- time zone (for example: America/Argentina/Cordoba)
    TZ: America/Argentina/Cordoba
    # --- TLS/SSL Certs configuration (selfsigned, custom or certbot letsencrypt)
    # --- if you have your own certs, put them into instances/tenant folder and
    # --- change this to *custom*
    certs: selfsigned
    # --- if you object storage service use selfsigned TLS/SSL certs, you mus to put
    # --- *callrec_device=s3-no-check-cert* in order to don't verify CA.
    callrec_device: s3-no-check-cert
    # --- PostgreSQL    
    postgres_port: 5432
    postgres_user: omnileads
    postgres_password: HJGKJHGDSAKJHK7856765DASDAS675765JHGJHSAjjhgjhaaa
    postgres_database: omnileads
    # --- *postgres* or *defaultdb* depend ...
    postgres_maintenance_db: postgres
    postgres_ssl: false
    # --- If you have a PGSQL cluster you can activated cluster mode
    # --- in order to split INSERT (RW node) & QUERIES (RO node)
    postgres_ha: false
    # --- OBJECT STORAGE
    # --- minio auth Web and Console admin params
    s3_http_admin_user: omnileads
    s3_http_admin_pass: jdhsgahkdgaskdasdhe2h4231hg4jjhgHJKG
    # --- bucket params    
    
    bucket_access_key: mYLcr7sx5vEbe7PO
    bucket_secret_key: v1Dl34Q29Bv6ruaWS7cUAEvSVfAtvGkR
    bucket_name: proxmox-deb
    # --- if your bucket doesn't need region, leave this value (us-east-1)
    bucket_region: us-east-1
    # --- Asterisk Manager Interface (AMI) user & password
    ami_user: omnileads
    ami_password: C12H17N2O4P_o98o98
    # --- Wombat Dialer API user & pass
    dialer_user: demoadmin
    dialer_password: demo
    # ---  kamailio shm & pkg memory params
    shm_size: 64
    pkg_size: 8
    # --- is the time in seconds that will last the https session when inactivity
    SCA: 3600
    # --- Ephemeral Credentials TTL (ECTTL) is the time in seconds            #
    # --- that will last the SIP credentials used to authenticate a SIP user  #
    # --- in the telephony system
    ECCTL: 28800
    # --- is the attempts a user has to enter an incorrect password in login
    LOGIN_FAILURE_LIMIT: 10
    # --- google maps integration credentials
    google_maps_api_key: NULL
    google_maps_center: '{ "lat": -31.416668, "lng": -64.183334 }'
    # --- SMTP server params, if you want to use your own SMTP, put true and
    # --- uncomment all necesary
    email_smtp_relay: false
    #email_backend:
    #email_default_from:
    #email_host:
    #email_password:
    #email_user:
    #email_port:
    #email_ssl_certfile:
    #email_ssl_keyfile:
    #email_use_ssl:
    #email_use_tls:

    # --- Docker Registry repo
    # --- If you are going to use another registry for the images, you must indicate here
    omlapp_repo: omnileads

    # --- Restore id request by restore filename
    #restore_file_timestamp: 1681215859

    # --- Integrations with external hosts
    # --- Request by docker-compose & promtail
    loki_host: 190.19.150.222
    # --- Request by Asterisk hep module
    homer_host: 190.19.150.222
    # --- Request by Web-Video Inbound Calls 
    #video_host: 

    # --- BACKUPs: in case of implementing a separate bucket for backups
    #backup_bucket: 
    # --- Restore: in case of implementing a separate bucket for restore
    #restore_bucket: 
    omnileads_ha: true

    ha_notification_email: mr_robot@mr_robot.com

#############################################################################################################
# -- In this section the hosts are grouped based on the type of deployment (AIO, Cluster & Cluster HA).     #
#############################################################################################################

omnileads_data:
  children:
    sql_1:
      hosts:
        tenant_aaa_sql_1:
        #tenant_bbb_sql_1:
      vars:
        omldata: true
        ha_rol: main
        postgres_host_ha: true
        netaddr: 172.16.101.0/16
        netprefix: 24
    sql_2:
      hosts:
        tenant_aaa_sql_2:
        #tenant_bbb_sql_2:
      vars:
        omldata: true
        ha_rol: backup        
        postgres_host_ha: true
        postgres_host_ha: true
        netaddr: 172.16.101.0/16
        netprefix: 24

omnileads_voice:
  children:
    voice_1:
      hosts:
        tenant_aaa_voice_1:
        #tenant_bbb_voice_1:
      vars:
        omlvoice: true
        ha_rol: main
    voice_2:
      hosts:
        tenant_aaa_voice_2:
        #tenant_bbb_voice_2:
      vars:
        omlvoice: true
        ha_rol: backup

omnileads_app:
  children:    
    app_1:
      hosts:
        tenant_aaa_app_1:
        #tenant_bbb_app_1:
      vars:
        omlapp: true
        ha_rol: main
    app_2:
      hosts:
        tenant_aaa_app_2:
        #tenant_bbb_app_2:
      vars:
        omlapp: true
        ha_rol: backup
        
omnileads_haproxy:
  children:
    haproxy_1:
      hosts:
        tenant_aaa_haproxy_1:
        #tenant_bbb_haproxy_1:
      vars:
        omlhaproxy: true
        ha_rol: main
    haproxy_2:
      hosts:
        tenant_aaa_haproxy_2:
        #tenant_bbb_haproxy_2:
      vars:
        omlhaproxy: true
        ha_rol: backup
