# Copyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---
# OMniLeads installation playbook
# It uses the files group_vars/all and inventory, as environment variables
# It uses the file /var/tmp/ansible/ansible.cfg, as configuration file

- name: Welcome to OMniLeads Matrix
  hosts:
    - omnileads_data
    - omnileads_voice
    - omnileads_app
    - omnileads_aio
    - ha_omnileads_sql
  gather_facts: True
  roles:
    - prerequisitos


- import_playbook: components/minio/playbook.yml
  when: 
    - bucket_url is not defined


- import_playbook: components/postgresql/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_data'] or inventory_hostname in groups['omnileads_aio']    
    - postgres_out == false
    - omnileads_ha is not defined


- import_playbook: components/postgresql/playbook_ha.yml
  when: 
    - inventory_hostname in groups['ha_omnileads_sql']


- import_playbook: components/redis/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_data'] or inventory_hostname in groups['omnileads_aio']    


- import_playbook: components/rtpengine/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_voice'] or inventory_hostname in groups['omnileads_aio']    
    - rtpengine_out == false


- import_playbook: components/keepalived/playbook.yml
  when: omnileads_ha is defined

  
- import_playbook: components/asterisk/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_voice'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/kamailio/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/fastagi/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/websockets/playbook.yml
  when: 
   - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/daphne/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/django/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/addons/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']
    - enterprise_edition == true


- import_playbook: components/cron/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/nginx/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/pstn_emulator/playbook.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/observability/prometheus.yml
  when: 
    - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']


- import_playbook: components/observability/promtail.yml
  when: 
    - loki_host is defined
    