# Copyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---
# OMniLeads installation playbook
# It uses the files group_vars/all and inventory, as environment variables
# It uses the file /var/tmp/ansible/ansible.cfg, as configuration file

- name: Welcome to OMniLeads Matrix
  hosts:
    - omnileads_data
    - omnileads_voice
    - omnileads_app
    - omnileads_haproxy
    - omnileads_aio
  gather_facts: True
  roles:
    - prerequisitos

- import_playbook: components/docker_compose/playbook.yml
  when: docker_compose is defined

- import_playbook: components/minio/playbook.yml
  when: 
    - bucket_url is not defined
    - docker_compose is not defined

- import_playbook: components/postgresql/playbook.yml
  when: 
    - omldata is defined or systemd is defined
    - postgres_out != true
    - docker_compose is not defined
    
- import_playbook: components/postgresql/playbook_ha.yml
  when: postgres_host_ha is defined

- import_playbook: components/redis/playbook.yml
  when: 
    - omldata is defined or systemd is defined
    - omnileads_ha is not defined
    - docker_compose is not defined

- import_playbook: components/redis/playbook_ha.yml
  when: omnileads_ha is defined

- import_playbook: components/sentinel/playbook.yml
  when: omnileads_ha is defined

- import_playbook: components/rtpengine/playbook.yml
  when: 
    - omlvoice is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/keepalived/playbook.yml
  when: omnileads_ha is defined

- import_playbook: components/haproxy/playbook.yml
  when: omnileads_ha is defined

- import_playbook: components/asterisk/playbook.yml
  when: 
    - omlvoice is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/kamailio/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/websockets/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/daphne/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined
- import_playbook: components/kamailio/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/websockets/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/daphne/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/django/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - omnileads_ha is not defined
    - docker_compose is not defined

- import_playbook: components/django/playbook_ha.yml
  when: 
    - omlapp is defined
    - omnileads_ha is defined

- import_playbook: components/addons/playbook.yml
  when: 
    - enterprise_edition == true
    - docker_compose is not defined

- import_playbook: components/cron/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/nginx/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/pstn_emulator/playbook.yml
  when: 
    - omlapp is defined or systemd is defined
    - docker_compose is not defined

- import_playbook: components/observability/prometheus.yml
  when: 
    - omlapp is defined or systemd is defined
    - omnileads_ha is not defined
    - docker_compose is not defined

- import_playbook: components/observability/promtail.yml
  when: 
    - docker_compose is not defined
    - omnileads_ha is not defined
    - loki_host is defined
