# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

---

- name: POSTGRS HA-Cluster Rocky Linux 8, installation and configuration
  hosts: omnileads_data
  tags:
    - all_components
    - postgres
    - install
    - upgrade
  
  vars:
    install_prefix: /opt/omnileads
    packages_url: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    repmgr_repo: https://dl.enterprisedb.com/default/release/get/{{ centos_postgresql_version }}/rpm
    pg_setup_location: "/usr/pgsql-/bin/postgresql--setup"
    pg_lib_location_no_version: /var/lib/pgsql
    pg_lib_location: "{{ pg_lib_location_no_version }}/{{ centos_postgresql_version }}/data"
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:

    - name: POSTGRES-HA Disable SELinux
      selinux:
        state: disabled

    - name: POSTGRES-HA setenforce 0
      command: setenforce 0

    - name: POSTGRES Disable the built-in PostgreSQL module
      command: dnf -y module disable postgresql

    - name: POSTGRES install repo for postgres
      command: dnf install -y "{{ packages_url }}"

    - name: Install Postgres from repository
      dnf:
        name:
          - postgresql{{ centos_postgresql_version }}
          - postgresql{{ centos_postgresql_version }}-server
          - postgresql{{ centos_postgresql_version }}-odbc
          - postgresql{{ centos_postgresql_version }}-plperl
          - postgresql{{ centos_postgresql_version }}-libs          
        state: latest

    - name: "Find out if PostgreSQL is initialized"
      stat:
        path: "{{ pg_lib_location }}/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-{{ centos_postgresql_version }}-setup initdb"
      when: not postgres_data.stat.exists

    #Se modifica la ip en la que escucha postgres para postgres interno no hace falta
    - name: Modify postgresql listen address
      lineinfile:
        path: '{{ pg_lib_location }}/postgresql.conf'
        regexp: "^#listen_addresses"
        line: "listen_addresses = '{{ omni_ip_lan }}'"
        state: present
      when:
        - postgres_host_ha is defined
        - omnileads_ha is not defined

    #Se modifica el timezone de postgres, para postgres interno no hace falta
    - name: Modify postgresql timezone
      lineinfile:
        path: '{{ pg_lib_location }}/postgresql.conf'
        regexp: "^timezone ="
        line: "timezone = 'UTC'"
        state: present
      when: postgres_host_ha is defined

    #Se modifica el data_directory en el caso de usar algun NFS o volumen externo
    - name: Modify postgresql data directory
      lineinfile:
        path: '{{ pg_lib_location }}/postgresql.conf'
        regexp: "^#data_directory"
        line: "data_directory = '{{ data_directory }}'"
        state: present
      when: data_directory is defined

    # Se modifica el pg_hba.conf a partir de template porque pg_hba es para python3 no anda en AIO
    - name: Copy pg_hba.conf AIO template file
      template:
        src: templates/pg_hba.conf.j2
        dest: '{{ pg_lib_location }}/pg_hba.conf'
      when: postgres_host_ha is not defined

    - name: Add line to pg_hba.conf host all omnileads subnet md5
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: '{{ postgres_user }}'
        source: '{{ netaddr }}'
        databases: all
        method: md5
      when: postgres_host_ha is defined

    - name: Add line to pg_hba.conf host all all 127.0.0.1 md5
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: all
        source: 127.0.0.1/32
        databases: all
        method: md5
      when: postgres_host_ha is defined

    - name: Add line to pg_hba.conf host postgres all 127.0.0.1 trust
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: all
        source: 127.0.0.1/32
        databases: all
        method: trust
      when: postgres_host_ha is defined

    - name: Start postgres service node
      service:
        name: "postgresql-{{ centos_postgresql_version }}"
        state: restarted
        enabled: no
      ignore_errors: yes

    - name: Creating user database
      shell: |
        existe=$(grep -c '^postgres:' /etc/passwd)
        if [ $existe -eq 1 ]; then
          sudo -u postgres psql -c "create user {{ postgres_user }} with encrypted password '{{ postgres_password}}';"
          sudo -u postgres psql -c "ALTER USER {{ postgres_user }} WITH SUPERUSER;"
        fi
      args:
        executable: /bin/bash

    # - name: Create user for omnileads app and asterisk
    #   postgresql_user:
    #     db:
    #     name: "postgres"
    #     password: "postgres"
    #     role_attr_flags: SUPERUSER
    #   when: 
    #     - upgrade_from_oml_1 is not defined
    #     - ha_rol == "main"

    - name: POSTGRESQL Create a new database with name {{ postgres_database }}
      postgresql_db:
        name: "{{ postgres_database }}"
        login_host: "{{ omni_ip_lan }}"
        login_password: "{{ postgres_password }}"
        login_user: "{{ postgres_user }}"
        port: "{{ postgres_port }}"
        maintenance_db: "{{ postgres_maintenance_db }}"
        state: present
      tags:
        - install
      when: 
        - upgrade_from_oml_1 is not defined
        - ha_rol == "main"

    - name: POSTGRESQL Create a new database with name {{ postgres_homer_db }}
      postgresql_db:
        name: "{{ postgres_homer_db }}"
        login_host: "{{ omni_ip_lan }}"
        login_password: "{{ postgres_password }}"
        login_user: "{{ postgres_user }}"
        port: "{{ postgres_port }}"
        maintenance_db: "{{ postgres_maintenance_db }}"
        state: present
      tags:
        - install
      when: 
        - upgrade_from_oml_1 is not defined
        - ha_rol == "main"

    - name: POSTGRESQL Adds plperl extension to the database {{ postgres_database }}
      postgresql_ext:
        name: plperl
        db: "{{ postgres_database }}"
        login_host: "localhost"
        login_password: "{{ postgres_password }}"
        login_user: "{{ postgres_user }}"
        port: "{{ postgres_port }}"
      tags:
        - install
      when: 
        - upgrade_from_oml_1 is not defined
        - ha_rol == "main"

    - name: POSTGRES HA Create postgres SSH directory
      file:
        mode: '0755'
        owner: postgres
        group: postgres
        path: "{{ pg_lib_location_no_version }}/.ssh/"
        state: directory

    - name: POSTGRES HA Copy SSH private key
      copy:
        src: "~/.ssh/id_rsa"
        dest: "{{ pg_lib_location_no_version }}/.ssh/id_rsa"
        owner: postgres
        group: postgres
        mode: '0600'

    - name: POSTGRES HA Copy SSH public key
      copy:
        src: "~/.ssh/id_rsa.pub"
        dest: "{{ pg_lib_location_no_version }}/.ssh/id_rsa.pub"
        owner: postgres
        group: postgres
        mode: '0644'

    - name: POSTGRES HA Add key to authorized keys file
      authorized_key:
        user: postgres
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        
    - name: Create of .pgpass files
      template:
        src: templates/.pgpass
        dest: "{{ pg_lib_location_no_version }}/.pgpass"
        mode: 0600
        owner: postgres
        group: postgres


###########################################################  HA Deploy ###########################################################
###########################################################  HA Deploy ###########################################################

    - debug: msg="=============================== Deploy High Availability ARQ ========================================="
      when: omnileads_ha is defined

    - debug: msg="=============================== Deploy High Availability ARQ ========================================="
      when: omnileads_ha is defined

    # - name: Add repmgr repo
    #   get_url:
    #     url: '{{ repmgr_repo }}'
    #     dest: /tmp/repmgr.repo
    #     mode: '0755'
    #   when: omnileads_ha is defined

    # - name: Install repmgr repo
    #   command: bash -x repmgr.repo
    #   args:
    #     chdir: /tmp
    #   when: omnileads_ha is defined

    - name: Install High Availability REMPGR
      dnf:
        name: repmgr{{ centos_postgresql_version }}
        state: latest
      when: omnileads_ha is defined

    - name: link ln -s repmgr
      file:
        src: /usr/pgsql-{{ centos_postgresql_version }}/bin/repmgr
        dest: /usr/local/bin/repmgr
        state: link
      when: omnileads_ha is defined

    - name: link ln -s repmgrd
      file:
        src: /usr/pgsql-{{ centos_postgresql_version }}/bin/repmgrd
        dest: /usr/local/bin/repmgrd
        state: link
      when: omnileads_ha is defined

    - name: mkdir archivelog
      file:
        path: "{{ pg_lib_location_no_version }}/archivelog"
        state: directory
        mode: '0755'
        owner: postgres
      when: omnileads_ha is defined

    - name: Template files High Availability are rendered
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        - { src: 'templates/ha_virtual_ip.sh', dest: '{{ pg_lib_location_no_version }}/ha_virtual_ip.sh' }
        - { src: 'templates/repmgr.j2', dest: '{{ pg_lib_location_no_version }}/repmgr.conf' }
        - { src: 'templates/omnileads_envars.j2', dest: '/etc/profile.d/omnileads_envars.sh' }
        - { src: 'templates/ifcfg-nic-main.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-{{ ha_vip_nic }}:0' }
        - { src: 'templates/ifcfg-nic-backup.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-{{ ha_vip_nic }}:1' }
      when: omnileads_ha is defined

    - name: Set permission postgres
      file:
        dest: "{{ item }}"
        owner: postgres
        group: postgres
        mode: '0744'
      with_items:
        - "{{ pg_lib_location_no_version }}/ha_virtual_ip.sh"
        - "{{ pg_lib_location_no_version }}/repmgr.conf"
        - "{{ pg_lib_location_no_version }}/archivelog"
      when: omnileads_ha is defined

    - name: Modify postgresql.conf High Availability
      lineinfile:
        dest: '{{ pg_lib_location }}/postgresql.conf'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - { regexp: "^#listen_addresses", line: "listen_addresses = '*'" }
        - { regexp: "^#archive_mode", line: "archive_mode = 'on'" }
        - { regexp: "^#archive_command", line: "archive_command = 'test ! -f {{ pg_lib_location_no_version }}/archivelog/%f && cp %p {{ pg_lib_location_no_version }}/archivelog/%f'" }
        - { regexp: "^#hot_standby", line: "hot_standby = on" }
        - { regexp: "^#shared_preload_libraries", line: "shared_preload_libraries = 'repmgr'"}
      when: omnileads_ha is defined

    - name: Copy omlpgsql-ha service
      copy:
        src: systemd/omlpgsql-ha.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '0644'
      when: omnileads_ha is defined

    - name: Copy repmgr{{ centos_postgresql_version }}.service
      copy:
        src: systemd/repmgr{{ centos_postgresql_version }}.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '0644'
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf local repmgr repmgr trust
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: local
        users: repmgr
        source:
        databases: repmgr
        method: trust
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf host repmgr repmgr subnet trust
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: repmgr
        source: '{{ netaddr }}'
        databases: repmgr
        method: trust
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf local replication repmgr trust
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: local
        users: repmgr
        source:
        databases: replication
        method: trust
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf local replication all peer
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: local
        users: all
        source:
        databases: replication
        method: peer
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf host replication repmgr subnet trust
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: repmgr
        source: '{{ netaddr }}'
        databases: replication
        method: trust
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf host replication all 127.0.0.1 ident
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: all
        source: 127.0.0.1/32
        databases: replication
        method: ident
      when: omnileads_ha is defined

    - name: Add line to pg_hba.conf host replication replicador subnet md5
      postgresql_pg_hba:
        dest: '{{ pg_lib_location }}/pg_hba.conf'
        contype: host
        users: replicador
        source: '{{ netaddr }}'
        databases: replication
        method: md5
      when: omnileads_ha is defined

    - name: Restart Postgresql service
      systemd:
        name: postgresql-{{ centos_postgresql_version }}
        state: restarted
        enabled: no
        daemon_reload: yes
      when: omnileads_ha is defined

    - name: Creating user and databases for HA
      shell: |
        sudo -u postgres psql -c "create user replicador with replication password '{{ postgres_password }}';"
        sudo -u postgres psql -c "create user repmgr WITH SUPERUSER;"
        sudo -u postgres psql -c "create database repmgr OWNER repmgr;" | true
      args:
        executable: /bin/bash
      when: omnileads_ha is defined

    - name: Stop postgresql-{{ centos_postgresql_version }} service
      service:
        name: postgresql-{{ centos_postgresql_version }}
        state: stopped
      when:
        - omnileads_ha is defined
        - ha_rol == 'backup'

    - name: Stop and enable repmgr service
      service:
        name: repmgr{{ centos_postgresql_version }}
        state: stopped
        enabled: yes
      when: omnileads_ha is defined
      ignore_errors: yes

    - name: REPMGR Config pg_basebackup CLUSTER HA
      shell: "cd {{ pg_lib_location_no_version }} && sudo -u postgres  pg_basebackup  -D '{{ pg_lib_location_no_version }}'/basebackup -Fp -Xs -P -R"
      when: 
        - omnileads_ha is defined
        - ha_rol == 'main'

    - name: REPMGR RSYNC main to readonly
      shell: "sudo -u postgres rsync -a {{ pg_lib_location_no_version }}/basebackup/  -e 'ssh -o StrictHostKeyChecking=no' root@{{ hostvars['sql_2'].omni_ip_lan }}:{{ pg_lib_location_no_version }}/{{ centos_postgresql_version }}/data/"
      when: 
        - omnileads_ha is defined      
        - ha_rol == 'main'

    - name: REPMGR Register like main role
      shell: "sudo -u postgres /usr/local/bin/repmgr -f {{ pg_lib_location_no_version }}/repmgr.conf master register -F"
      when: 
        - omnileads_ha is defined
        - ha_rol == 'main'

    - name: REPMGR readonly clone from main
      shell: "sudo -u postgres /usr/local/bin/repmgr -h {{ hostvars['sql_1'].omni_ip_lan }} -U repmgr -d repmgr -f {{ pg_lib_location_no_version }}/repmgr.conf standby clone -F"
      when: 
        - omnileads_ha is defined
        - ha_rol == 'backup'

    - name: REPMGR Config start postgresql-{{ centos_postgresql_version }} service node RO
      service:
        name: postgresql-{{ centos_postgresql_version }}
        state: started
      when:
        - omnileads_ha is defined
        - ha_rol == 'backup'

    - name: REPMGR Register like readonly node
      shell: "sudo -u postgres /usr/local/bin/repmgr -f {{ pg_lib_location_no_version }}/repmgr.conf standby register -F"
      when: 
        - omnileads_ha is defined
        - ha_rol == 'backup'

    - name: REPMGR Config Start postgres-ha virtual ip service
      service:
        name: omlpgsql-ha
        state: started
        enabled: yes
      when: omnileads_ha is defined
      ignore_errors: yes

    - name: REPMGR Config Start repmgr service
      service:
        name: repmgr{{ centos_postgresql_version }}
        state: started
        enabled: yes
      when: omnileads_ha is defined
      ignore_errors: yes