# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: POSTGRESQL component deploy
  hosts: 
    - omnileads_data
    - omnileads_aio
  tags:
    - all_components
    - data
    - postgres    

  tasks:
    - name: POSTGRESQL Set environment variables for this installation
      template:
        src: "{{ pgsql_repo_path }}templates/postgres.env"
        dest: /etc/default/postgres.env
        mode: '0664'
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
      tags:
        - install
        - upgrade
        - update

    - name: POSTGRESQL Copy systemd file
      template:
        src: "{{ pgsql_repo_path }}templates/postgresql.service"
        dest: /etc/systemd/system/postgresql.service
      tags: 
        - install
        - upgrade
        - update

    - name: POSTGRESQL Pull image
      command: podman pull --quiet {{ postgres_img }}
      register: podman_pull
      until: podman_pull is success
      tags:
        - install
        - upgrade
        - update

    - name: POSTGRESQL Enable and start service
      systemd:
        name: postgresql.service
        state: started
        enabled: yes
        daemon_reload: yes
      tags:
        - install
        - upgrade
        - update
      when: omnileads_ha is not defined

- name: POSTGRESQL Include High Availability playbook
  import_playbook: ha.yml
  when: omnileads_ha is defined
  
- name: POSTGRESQL Include Prometheus playbook
  import_playbook: prometheus.yml
  