
# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

---

- name: POSTGRES HA-Cluster Takeover Main Node
  hosts: omnileads_aio
  tags:
    - pgsql_node_takeover_main
  vars:
    postgres_env: /etc/default/postgres.env
  
  tasks:

    - name: POSTGRESQL Stopped postgres service HA
      service:
        name: postgresql.service
        state: stopped
        enabled: no
      when:
        - ha_role == "backup"
    
    - name: POSTGRESQL Stopped
      pause:
        seconds: 10
      when:
        - ha_role == "backup"

    - name: POSTGRESQL Recovery BACKUP RO Repmgr standby clone
      shell: "podman run  --cgroups=no-conmon --sdnotify=conmon --replace --rm --network=host --env-file={{ postgres_env }} --name=oml-repmgr-dry-run --volume=/etc/omnileads/pgpass:/var/lib/postgresql/.pgpass  --volume=oml_postgres:/var/lib/postgresql/data --volume=/etc/omnileads/repmgr.conf:/etc/postgresql/repmgr.conf --user=postgres {{ postgres_ha_img }} repmgr -h {{ aio_1 }} -U repmgr -d repmgr -f /etc/postgresql/repmgr.conf standby clone --dry-run"
      args:
        executable: /bin/bash
      register: dry_run
      when:
        - ha_role == "backup"

    - name: POSTGRESQL Recovery BACKUP RO Repmgr standby clone -F
      shell: "podman run  --cgroups=no-conmon --sdnotify=conmon --replace --rm --network=host --env-file={{ postgres_env }} --name=oml-repmgr-dry-run --volume=/etc/omnileads/pgpass:/var/lib/postgresql/.pgpass  --volume=oml_postgres:/var/lib/postgresql/data --volume=/etc/omnileads/repmgr.conf:/etc/postgresql/repmgr.conf --user=postgres {{ postgres_ha_img }} repmgr -h {{ aio_1 }} -U repmgr -d repmgr -f /etc/postgresql/repmgr.conf standby clone -F"
      args:
        executable: /bin/bash
      register: dry_run
      when: 
        - ha_role == "backup"

    - name: POSTGRESQL Start postgresql after resync
      service:
        name: postgresql
        state: started
      when: 
        - ha_role == "backup"
    
    - name: POSTGRESQL Start
      pause:
        seconds: 10
      when:
        - ha_role == "backup"

    - name: POSTGRESQL Recovery BACKUP RO Repmgr standby register
      shell: "podman run  --cgroups=no-conmon --sdnotify=conmon --replace --rm --network=host --env-file={{ postgres_env }} --name=oml-repmgr-stand-by-reg --volume=/etc/omnileads/pgpass:/var/lib/postgresql/.pgpass  --volume=oml_postgres:/var/lib/postgresql/data --volume=/etc/omnileads/repmgr.conf:/etc/postgresql/repmgr.conf --user=postgres {{ postgres_ha_img }} repmgr -h {{ aio_2 }} -U repmgr -d repmgr -f /etc/postgresql/repmgr.conf standby register -F"
      args:
        executable: /bin/bash
      when: 
        - ha_role == "backup"    