# qa_repoCopyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---
- name: WEBSOCKETS OMniLeads Websocket installation and configuration
  hosts: 
    - omnileads_app
    - omnileads_aio
  vars:
    img_repo: '{{ img_registry_core_url }}/{{ img_registry_core_repo }}/websockets'
    network: omnileads
  tags:
    - all_components
    - app
    - websockets
  tasks:

  - name: WEBSOCKETS environment variables for this installation
    template:
      src: "{{ websockets_repo_path }}templates/websockets.env"
      dest: /etc/default/websockets.env
      mode: 664
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - install
      - upgrade
      - update

  - name: WEBSOCKETS Copy systemd service
    template:
      src: "{{ websockets_repo_path }}templates/websockets.service"
      dest: /etc/systemd/system/websockets.service
    tags:
      - install
      - upgrade
      - update

  - name: WEBSOCKETS Pull image
    command: podman pull --quiet {{ img_repo }}:{{ websockets_version }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update

  - name: WEBSOCKETS Enable and start Websockets service
    systemd:
      name: websockets.service
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
      - install

  - name: WEBSOCKETS Restart Websockets service
    systemd:
      name: websockets.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade
      - restart
      - restart_websockets
    when:       
      - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']    