# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- name: KEEPALIVED installation and configuration
  hosts: 
    - omnileads_voice
    - omnileads_haproxy
    - omnileads_app
  tags:
    - install
    - keepalived
  vars:
    img_repo: '{{ container_image_registry }}/omnileads/asterisk'
  tasks:

  - name: KEEPALIVED Install High Availability TOOLs
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - keepalived
    when: ansible_os_family == "RedHat"

  - name: KEEPALIVED Install High Availability TOOLs
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - keepalived
    when: ansible_os_family == "Debian"

  - name: KEEPALIVED Keepalived Voice config provissioning
    template: 
      src: "{{ keepalived_repo_path }}templates/keepalived_asterisk.j2"
      dest: /etc/keepalived/keepalived.conf
    when:
      - inventory_hostname in groups['omnileads_voice']
    tags:
      - upgrade

  - name: KEEPALIVED check_component.sh script Voice provissioning
    template: 
      src: "{{ keepalived_repo_path }}templates/check_ha_asterisk.j2"
      dest: /usr/bin/check_ha.sh
      mode: 755
    when:
      - inventory_hostname in groups['omnileads_voice']
    tags:
      - upgrade

  - name: KEEPALIVED transition to master script
    template: 
      src: "{{ keepalived_repo_path }}templates/asterisk_transition.sh"
      dest: /usr/bin/asterisk_transition.sh
      mode: 755
    when:
      - inventory_hostname in groups['omnileads_voice']
    tags:
      - upgrade

  - name: KEEPALIVED Keepalived HAProxy config provissioning
    template: 
      src: "{{ keepalived_repo_path }}templates/keepalived_haproxy.j2" 
      dest: /etc/keepalived/keepalived.conf
    when:
      - omlhaproxy is defined
    tags:
      - upgrade

  - name: KEEPALIVED check_component.sh script HAProxy provissioning
    template: 
      src: "{{ keepalived_repo_path }}templates/check_ha_haproxy.j2"
      dest: /usr/bin/check_ha.sh
      mode: 755
    when:
      - omlhaproxy is defined
    tags:
      - upgrade

  - name: KEEPALIVED Keepalived CRON config provissioning
    template: 
      src: "{{ keepalived_repo_path }}templates/keepalived_cron.j2" 
      dest: /etc/keepalived/keepalived.conf
    when:
      - inventory_hostname in groups['omnileads_app']
    tags:
      - upgrade

  - name: KEEPALIVED check_component.sh script CRON provissioning
    template: 
      src: "{{ keepalived_repo_path }}templates/check_ha_cron.j2"
      dest: /usr/bin/check_ha.sh
      mode: 755
    when:
      - inventory_hostname in groups['omnileads_app']
    tags:
      - upgrade

  - name: KEEPALIVED Start and enable Systemd High Availability TOOLs
    systemd:
      name: keepalived.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade

