# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

---

- name: REDIS OMniLeads Redis Sentinel component deploy
  hosts: 
    - aio_1
    - aio_2
    - app_2
    - haproxy_1
  tags:
    - all_components
    - app
    - redis
    - sentinel
  vars:
    img_repo: '{{ container_image_registry }}/omnileads/redis'
    img_repo_ha: '{{ container_image_registry }}/omnileads/redis'
    img_prometheus_repo: 'docker.io/oliver006/redis_exporter'
  tasks:

  - name: REDIS sentinel copy systemd service
    template:
      src: "{{ sentinel_repo_path }}templates/sentinel.service"
      dest: /etc/systemd/system/sentinel.service
    tags:
      - install
      - upgrade
    when: omnileads_ha is defined  

  - name: REDIS Set Sentinel environment variables for this installation
    template:
      src: "{{ sentinel_repo_path }}templates/sentinel.env"
      dest: /etc/default/sentinel.env
      mode: 664
      owner: '{{ usuario }}'
      group: '{{ usuario }}'
    tags:
      - install
      - upgrade
    when: omnileads_ha is defined

  - name: REDIS Sentinel Pull image
    command: podman pull --quiet {{ img_repo_ha }}:{{ redis_ha_version }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
    when: omnileads_ha is defined 

  - name: REDIS Sentinel Enable and start service
    systemd:
      name: sentinel.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade
    when: omnileads_ha is defined 
