# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: DJANGO OMniLeads application installation
  hosts: omnileads-app
  tags:
    - aio
    - app
    - django
  vars:
    packages_url: https://fts-public-packages.s3.amazonaws.com
    oml_utilities_repo: https://gitlab.com/omnileads/omlutilities.git
    virtualenv_package: "{{ packages_url }}/virtualenv/virtualenv_{{ virtualenv_version }}_amd64.deb"
    INSTALL_PREFIX: "/opt/omnileads"

  tasks:

  - name: Install Django required packages
    apt:
      name:
        - postgresql-client
        - libcairo2
        - sox
        - texinfo
        - acl
        - lame
        - unzip
        - bind9-utils
        - gettext
        - libpython3.9
        - sudo
      state: latest

  # Create file .pgpass
  - name: DJANGO Create file .pgpass
    template:
      src: "{{ django_repo_path }}templates/.pgpass"
      dest: "{{ item }}.pgpass"
      mode: 060
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    with_items:
      - "{{ django_deploy_path }}"
      - /root/
    when: postgres_host != "localhost"
    tags:
      - upgrade

  - name: Set Django environment variables for this installation
    template:
      src: "{{ django_repo_path }}templates/virtualenv.env"
      dest: /etc/default/omnileads_django.env
      mode: 666
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - upgrade

  ########### WA temporal permisos dajango .env #################
  ########### WA temporal permisos dajango .env #################
  - name: Change file ownership, group and permissions
    file:
      path:  /etc/default/omnileads_django.env
      owner: omnileads
      group: omnileads
      mode: '0666'
    tags:
      - upgrade

  # Create extension plperl, when the OMniLeads PostgreSQL package is not used
  - name: Create extension plperl
    shell: PGUSER={{ postgres_user }} PGDATABASE={{ postgres_database }} PGHOST={{ postgres_host }} PGPORT={{ postgres_port }} PGPASSWORD={{ postgres_password }} psql -c "CREATE EXTENSION plperl;"
    args:
      executable: /bin/bash
    when: postgres_cloud == "true"
    ignore_errors: yes
    when:
      - postgres_host is defined
      - postgres_cloud == "true"

  # Se instala el paquete asterisk
  - name: DJANGO App Download virtual_{{ virtualenv_version }} package (from s3 source)
    get_url:
      url: "{{ virtualenv_package }}"
      dest: /tmp/
    register: s3_download

  - name: DJANGO App Install virtualenv package {{ virtualenv_version }}
    command: dpkg -i /tmp/virtualenv_{{ virtualenv_version }}_amd64.deb
    tags: apt

  - name: Modify django-uwsgi listen address
    lineinfile:
      path: '{{ INSTALL_PREFIX }}/run/oml_uwsgi.ini'
      regexp: "socket = 0.0.0.0:8098"
      line: "socket = {{ omni_ip_lan }}:{{ uwsgi_port }}"
      state: present

  # Restart OMniLeads service
  - name: DJANGO Restart OMniLeads service
    systemd:
      name: omnileads
      state: restarted
      enabled: yes
      daemon_reload: yes

  # Restart OMniLeads Daphne service
  - name: DJANGO Restart OMniLeads Daphne service
    systemd:
      name: omnileads-daphne
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: DJANGO reset OML admin password
    shell: /opt/omnileads/bin/manage.sh cambiar_admin_password
