# Copyright (C) 2024 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: DJANGO High Availability OMniLeads app deploy
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - all_components
    - aio
    - app
    - django
  vars:
    INSTALL_PREFIX: "/opt/omnileads"
    
  tasks:

    - name: DJANGO run django_commands
      shell: "podman run --network=host --env-file /etc/default/django.env --volume=django_static:/opt/omnileads/static --rm {{ omnileads_img }} /opt/omnileads/bin/django_commands.sh"
      tags:
        - install
      when: 
      - omnileads_ha is defined
      - ha_role == "main"
    
    - name: DJANGO run migrations
      shell: "podman run --network=host --env-file /etc/default/django.env --volume=django_static:/opt/omnileads/static --rm {{ omnileads_img }} /opt/omnileads/bin/django_migrations.sh"
      tags:  
        - upgrade
      when: 
        - omnileads_ha is defined
        - ha_role == "main"

    - name: DJANGO Enable and start systemd UWSGI service
      systemd:
        name: omnileads.service
        state: started
        enabled: no
        daemon_reload: yes
      tags:
        - install
      when: 
        - omnileads_ha is defined
        - ha_role == "main"

    - name: DJANGO reset admin pass
      shell: "podman run --network=host --env-file /etc/default/django.env --rm {{ omnileads_img }} python /opt/omnileads/ominicontacto/manage.py cambiar_admin_password"
      tags:
        - install
      when: 
        - omnileads_ha is defined
        - ha_role == "main"

    - name: DJANGO Restart systemd UWSGI service
      systemd:
        name: omnileads.service
        state: restarted
        enabled: no
        daemon_reload: yes
      tags:
        - upgrade
        - restart
        - restart_django
        - restart_core
      when: 
        - omnileads_ha is defined
        - ha_role == "main"