# Copyright (C) 2022 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: DJANGO OMniLeads application installation
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - all_components
    - aio
    - app
    - django
  vars:
    img_repo: '{{ container_image_registry }}/{{ omlapp_repo }}/omlapp'
    INSTALL_PREFIX: "/opt/omnileads"

  tasks:

  - name: DJANGO environment variables for this installation
    template:
      src: "{{ django_repo_path }}templates/django.env"
      dest: /etc/default/django.env
      mode: 666
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - install
      - upgrade

  - name: DJANGO Copy systemd service
    template:
      src: "{{ django_repo_path }}templates/django.service"
      dest: /etc/systemd/system/omnileads.service
    tags:
      - install
      - upgrade
    
  - name: DJANGO Pull image
    command: podman pull --quiet {{ img_repo }}:{{ omnileads_version }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
    when: enterprise_edition == false

  - name: DJANGO Enterprise Pull image
    command: podman pull --quiet {{ img_repo }}:{{ omnileads_version }}-enterprise
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
    when: enterprise_edition == true

  - name: POSTGRESQL Create a new database with name {{ postgres_database }}
    postgresql_db:
      name: "{{ postgres_database }}"
      login_host: "{{ postgres_host }}"
      login_password: "{{ postgres_password }}"
      login_user: "{{ postgres_user }}"
      port: "{{ postgres_port }}"
      maintenance_db: "{{ postgres_maintenance_db }}"
      state: present
    tags:
      - install
    when: 
      - upgrade_from_oml_1 is not defined 
      - postgres_out == true
      
  - name: Scalable Tunings; UWSGI Copy custom uwsgi.ini
    template:
      src: "{{ django_repo_path }}templates/uwsgi.ini"
      dest: /etc/omnileads/uwsgi.ini
      mode: 666
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    when: 
      - inventory_hostname in groups['omnileads_app']
      - scalable_tunings is defined

  - name: DJANGO Enable and start systemd service
    systemd:
      name: omnileads.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - install
      - upgrade

  - name: POSTGRESQL Adds plperl extension to the database {{ postgres_database }}
    shell: podman exec -it oml-django-server psql -U {{ postgres_user }} -d {{ postgres_database }} -c "CREATE EXTENSION IF NOT EXISTS plperl;" 
    tags:
      - install
    when: 
      - upgrade_from_oml_1 is not defined 
      - restore_file_timestamp is not defined
      - postgres_out == true


  # - name: Reset Admin Pass
  #   shell: "oml_manage --reset_pass"
  #   args:
  #     executable: /bin/bash
  #   tags:
  #     - install