# qa_repoCopyright (C) 2023 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

---

- name: DJANGO OMniLeads application installation
  hosts: 
    - omnileads_app
    - omnileads_aio
  tags:
    - all_components
    - aio
    - app
    - django
  vars:
    INSTALL_PREFIX: "/opt/omnileads"

  tasks:

  - name: DJANGO environment variables for this installation
    template:
      src: "{{ django_repo_path }}templates/django.env"
      dest: /etc/default/django.env
      mode: 666
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
    tags:
      - install
      - upgrade
      - update

  - name: DJANGO Copy systemd service
    template:
      src: "{{ django_repo_path }}templates/django.service"
      dest: /etc/systemd/system/omnileads.service
    tags:
      - install
      - upgrade
      - update
    
  - name: DJANGO Pull image
    command: podman pull --quiet {{ omnileads_img }}
    register: podman_pull
    until: podman_pull is success
    tags:
      - install
      - upgrade
      - update

  - name: POSTGRESQL Create a new database with name {{ postgres_database }}
    postgresql_db:
      name: "{{ postgres_database }}"
      login_host: "{{ postgres_host }}"
      login_password: "{{ postgres_password }}"
      login_user: "{{ postgres_user }}"
      port: "{{ postgres_port }}"
      maintenance_db: "{{ postgres_maintenance_db }}"
      state: present
    tags:
      - install
    when: 
      - upgrade_from_oml_1 is not defined 
      - postgres_out == true

  - name: DJANGO run migrations collectstatic & others commands
    shell: "podman run --network=host --env-file /etc/default/django.env --volume=django_static:/opt/omnileads/static  {{ omnileads_img }} /opt/omnileads/bin/django_commands.sh"
    tags:
      - install
      - upgrade

  - name: DJANGO Enable and start systemd UWSGI service
    systemd:
      name: omnileads.service
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
      - install

  - name: DJANGO reset admin pass
    shell: "podman run --network=host --env-file /etc/default/django.env {{ omnileads_img }} python /opt/omnileads/ominicontacto/manage.py cambiar_admin_password"
    tags:
      - install

  - name: DJANGO Restart systemd UWSGI service
    systemd:
      name: omnileads.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    tags:
      - upgrade
      - restart
      - restart_django
      - restart_core
    when:       
      - inventory_hostname in groups['omnileads_app'] or inventory_hostname in groups['omnileads_aio']    
